export const foodIcons = {
    "Apple": "🍎",
    "Banana": "🍌",
    "Bread": "🍞",
    "Cheese": "🧀",
    "Chicken": "🍗",
    "Rice": "🍚",
    "Pasta": "🍝",
    "Egg": "🥚",
    "Milk": "🥛",
    "Fish": "🐟",
    "Carrot": "🥕",
    "Potato": "🥔",
    "Tomato": "🍅",
    "Broccoli": "🥦",
    "Onion": "🧅",
    "Garlic": "🧄",
    "Orange": "🍊",
    "Grapes": "🍇",
    "Strawberry": "🍓",
    "Watermelon": "🍉",
    "Pizza": "🍕",
    "Hamburger": "🍔",
    "Hot Dog": "🌭",
    "French Fries": "🍟",
    "Salad": "🥗",
    "Soup": "🥣",
    "Sandwich": "🥪",
    "Cake": "🍰",
    "Cookie": "🍪",
    "Ice Cream": "🍦",
    "Coffee": "☕",
    "Tea": "🍵",
    "Juice": "🍹",
    "Water": "💧",
    "Doughnut": "🍩",
    "Candy": "🍬",
    "Chocolate": "🍫",
    "Popcorn": "🍿",
    "Honey": "🍯",
    "Sugar": "🍚",
    "Salt": "🧂",
    "Pepper": "🌶️",
    "Oil": "🍾",
    "Vinegar": "🍾",
    "Butter": "🧈",
    "Jam": "🍓",
    "Yogurt": "🍦",
    "Cereal": "🥣",
    "Pancake": "🥞",
    "Sausage": "🌭",
};
export  const animalIcons = {
    "Dog": "🐶",
    "Cat": "🐱",
    "Lion": "🦁",
    "Elephant": "🐘",
    "Tiger": "🐯",
    "Horse": "🐎",
    "Bird": "🐦",
    "Fish": "🐟",
    "Rabbit": "🐰",
    "Chicken": "🐔",
    "Wolf": "🐺",
    "Monkey": "🐵",
    "Bear": "🐻",
    "Dolphin": "🐬",
    "Shark": "🦈",
    "Cow": "🐄",
    "Pig": "🐷",
    "Sheep": "🐑",
    "Goat": "🐐",
    "Deer": "🦌",
    "Fox": "🦊",
    "Panda": "🐼",
    "Penguin": "🐧",
    "Giraffe": "🦒",
    "Zebra": "🦓",
    "Kangaroo": "🦘",
    "Owl": "🦉",
    "Duck": "🦆",
    "Snake": "🐍",
    "Crocodile": "🐊",
    "Turtle": "🐢",
    "Frog": "🐸",
    "Lizard": "🦎",
    "Spider": "🕷️",
    "Bee": "🐝",
    "Ant": "🐜",
    "Butterfly": "🦋",
    "Whale": "🐳",
    "Octopus": "🐙",
    "Crab": "🦀",
    "Lobster": "🦞",
    "Shrimp": "🦐",
    "Pigeon": "🕊️",
    "Eagle": "🦅",
    "Flamingo": "🦩",
    "Rhino": "🦏",
    "Hippo": "🦛",
    "Snail": "🐌",
    "Hedgehog": "🦔",
    "Squirrel": "🐿️",
    "Otter": "🦦",
    "Raccoon": "🦝",
    "Bat": "🦇"
  };

  export const colorIcons = {
    "Red": "❤️",
  "Blue": "💙",
  "Green": "💚",
  "Yellow": "💛",
  "Orange": "🧡",
  "Purple": "💜",
  "Black": "🖤",
  "White": "🤍",
  "Brown": "🤎",
  "Pink":"🌺",
  "Gold": "💰",
  "LightBlue": "🌐",
  "Silver": "🥈",
  "Gray": "🗻🌑"
  };

  // FIXED: data and icons for the previously unfinished item categories.
  export const furnitureIcons = {
    "Chair": "🪑",
    "Table": "🪑",
    "Sofa": "🛋️",
    "Bed": "🛏️",
    "Desk": "🖥️",
    "Wardrobe": "🚪",
    "Bookshelf": "📚",
    "Cabinet": "🗄️",
    "Dresser": "🗄️",
    "Nightstand": "🛏️",
    "Armchair": "🛋️",
    "Stool": "🪑",
    "Bench": "🪑",
    "Lamp": "💡",
    "Mirror": "🪞",
    "Rug": "🧶",
    "Curtains": "🪟",
    "Clock": "🕰️",
    "Television": "📺",
    "Coffee Table": "☕",
    "Dining Table": "🍽️",
    "Rocking Chair": "🪑",
    "Bunk Bed": "🛏️",
    "Crib": "🛏️",
    "Ottoman": "🛋️",
    "Chest of Drawers": "🗄️"
  };

  export const vehicleIcons = {
    "Car": "🚗",
    "Bus": "🚌",
    "Bicycle": "🚲",
    "Motorcycle": "🏍️",
    "Train": "🚆",
    "Airplane": "✈️",
    "Helicopter": "🚁",
    "Boat": "⛵",
    "Ship": "🚢",
    "Truck": "🚚",
    "Taxi": "🚕",
    "Ambulance": "🚑",
    "Fire Truck": "🚒",
    "Police Car": "🚓",
    "Scooter": "🛴",
    "Tractor": "🚜",
    "Subway": "🚇",
    "Tram": "🚊",
    "Van": "🚐",
    "Rocket": "🚀",
    "Hot Air Balloon": "🎈",
    "Canoe": "🛶",
    "Kayak": "🛶",
    "Ferry": "⛴️",
    "Skateboard": "🛹"
  };

  export const clothesIcons = {
    "Shirt": "👔",
    "T-Shirt": "👕",
    "Pants": "👖",
    "Jeans": "👖",
    "Dress": "👗",
    "Skirt": "👗",
    "Shorts": "🩳",
    "Jacket": "🧥",
    "Coat": "🧥",
    "Sweater": "👕",
    "Hoodie": "👕",
    "Suit": "🤵",
    "Socks": "🧦",
    "Shoes": "👟",
    "Boots": "🥾",
    "Sandals": "🩴",
    "Hat": "🎩",
    "Cap": "🧢",
    "Scarf": "🧣",
    "Gloves": "🧤",
    "Belt": "🪢",
    "Tie": "👔",
    "Pajamas": "🥱",
    "Swimsuit": "🩱",
    "Raincoat": "🧥"
  };

  export const shapeIcons = {
    "Circle": "⚪",
    "Square": "🟦",
    "Triangle": "🔺",
    "Rectangle": "▬",
    "Oval": "⬭",
    "Diamond": "🔶",
    "Star": "⭐",
    "Heart": "❤️",
    "Pentagon": "⬠",
    "Hexagon": "⬡",
    "Octagon": "🛑",
    "Crescent": "🌙",
    "Cross": "➕",
    "Arrow": "➡️",
    "Cube": "🧊",
    "Sphere": "🔵",
    "Cylinder": "🥫",
    "Cone": "🔺"
  };

  export  const itemIcons = {
    ...foodIcons,
    ...animalIcons,
    ...colorIcons,
    ...furnitureIcons,
    ...vehicleIcons,
    ...clothesIcons,
    ...shapeIcons
};

  const iconMapToItems = (iconMap) =>
    Object.entries(iconMap).map(([name, icon]) => ({ name, icon }));

  export const furnitureItems = iconMapToItems(furnitureIcons);
  export const vehicleItems = iconMapToItems(vehicleIcons);
  export const clothesItems = iconMapToItems(clothesIcons);
  export const shapeItems = iconMapToItems(shapeIcons);
  export const animals = [
    { name: "Dog", icon: "🐶" },
    { name: "Cat", icon: "🐱" },
    { name: "Lion", icon: "🦁" },
    { name: "Elephant", icon: "🐘" },
    { name: "Tiger", icon: "🐯" },
    { name: "Horse", icon: "🐎" },
    { name: "Bird", icon: "🐦" },
    { name: "Fish", icon: "🐟" },
    { name: "Rabbit", icon: "🐰" },
    { name: "Chicken", icon: "🐔" },
    { name: "Wolf", icon: "🐺" },
    { name: "Monkey", icon: "🐵" },
    { name: "Bear", icon: "🐻" },
    { name: "Dolphin", icon: "🐬" },
    { name: "Shark", icon: "🦈" },
    { name: "Cow", icon: "🐄" },
    { name: "Pig", icon: "🐷" },
    { name: "Sheep", icon: "🐑" },
    { name: "Goat", icon: "🐐" },
    { name: "Deer", icon: "🦌" },
    { name: "Fox", icon: "🦊" },
    { name: "Panda", icon: "🐼" },
    { name: "Penguin", icon: "🐧" },
    { name: "Giraffe", icon: "🦒" },
    { name: "Zebra", icon: "🦓" },
    { name: "Kangaroo", icon: "🦘" },
    { name: "Owl", icon: "🦉" },
    { name: "Duck", icon: "🦆" },
    { name: "Snake", icon: "🐍" },
    { name: "Crocodile", icon: "🐊" },
    { name: "Turtle", icon: "🐢" },
    { name: "Frog", icon: "🐸" },
    { name: "Lizard", icon: "🦎" },
    { name: "Spider", icon: "🕷️" },
    { name: "Bee", icon: "🐝" },
    { name: "Ant", icon: "🐜" },
    { name: "Butterfly", icon: "🦋" },
    { name: "Whale", icon: "🐳" },
    { name: "Octopus", icon: "🐙" },
    { name: "Crab", icon: "🦀" },
    { name: "Lobster", icon: "🦞" },
    { name: "Shrimp", icon: "🦐" },
    { name: "Pigeon", icon: "🕊️" },
    { name: "Eagle", icon: "🦅" },
    { name: "Flamingo", icon: "🦩" },
    { name: "Rhino", icon: "🦏" },
    { name: "Hippo", icon: "🦛" },
    { name: "Snail", icon: "🐌" },
    { name: "Hedgehog", icon: "🦔" },
    { name: "Squirrel", icon: "🐿️" },
    { name: "Otter", icon: "🦦" },
    { name: "Raccoon", icon: "🦝" },
    { name: "Bat", icon: "🦇" },
];

 export const foodItems = [
    { name: "Apple", icon: "🍎" },
    { name: "Banana", icon: "🍌" },
    { name: "Bread", icon: "🍞" },
    { name: "Cheese", icon: "🧀" },
    { name: "Chicken", icon: "🍗" },
    { name: "Rice", icon: "🍚" },
    { name: "Pasta", icon: "🍝" },
    { name: "Egg", icon: "🥚" },
    { name: "Milk", icon: "🥛" },
    { name: "Fish", icon: "🐟" },
    { name: "Carrot", icon: "🥕" },
    { name: "Potato", icon: "🥔" },
    { name: "Tomato", icon: "🍅" },
    { name: "Broccoli", icon: "🥦" },
    { name: "Onion", icon: "🧅" },
    { name: "Garlic", icon: "🧄" },
    { name: "Orange", icon: "🍊" },
    { name: "Grapes", icon: "🍇" },
    { name: "Strawberry", icon: "🍓" },
    { name: "Watermelon", icon: "🍉" },
    { name: "Pizza", icon: "🍕" },
    { name: "Hamburger", icon: "🍔" },
    { name: "Hot Dog", icon: "🌭" },
    { name: "French Fries", icon: "🍟" },
    { name: "Salad", icon: "🥗" },
    { name: "Soup", icon: "🥣" },
    { name: "Sandwich", icon: "🥪" },
    { name: "Cake", icon: "🍰" },
    { name: "Cookie", icon: "🍪" },
    { name: "Ice Cream", icon: "🍦" },
    { name: "Coffee", icon: "☕" },
    { name: "Tea", icon: "🍵" },
    { name: "Juice", icon: "🍹" },
    { name: "Water", icon: "💧" },
    { name: "Doughnut", icon: "🍩" },
    { name: "Candy", icon: "🍬" },
    { name: "Chocolate", icon: "🍫" },
    { name: "Popcorn", icon: "🍿" },
    { name: "Honey", icon: "🍯" },
    { name: "Sugar", icon: "🍚" }, // Reusing rice icon for sugar, or can find a better one
    { name: "Salt", icon: "🧂" },
    { name: "Pepper", icon: "🌶️" }, // Reusing pepper icon for spice, or can find a better one
    { name: "Oil", icon: "🍾" }, // Reusing bottle icon for oil, or can find a better one
    { name: "Vinegar", icon: "🍾" }, // Reusing bottle icon for vinegar
    { name: "Butter", icon: "🧈" },
    { name: "Jam", icon: "🍓" }, // Reusing strawberry icon for jam
    { name: "Yogurt", icon: "🍦" }, // Reusing ice cream icon for yogurt
    { name: "Cereal", icon: "🥣" }, // Reusing bowl icon for cereal
    { name: "Pancake", icon: "🥞" },
    { name: "Sausage", icon: "🌭" }, // Reusing hot dog icon for sausage
];

export const colorsItem = [
  { name: "Red", icon: "❤️" },
  { name: "Orange", icon: "🧡" },
  { name: "Yellow", icon: "💛" },
  { name: "Green", icon: "💚" },
  { name: "LightBlue", icon: "🌐" },
  { name: "Blue", icon: "💙" },
  { name: "Purple", icon: "💜" },
  { name: "Brown", icon: "🤎" },
  { name: "White", icon: "🤍" },
  { name: "Black", icon: "🖤" },
  { name: "Pink", icon: "🌺" },
  { name: "Gold", icon: "💰" },
  { name: "Silver", icon: "🥈" },
  { name: "Gray", icon: "🗻🌑" },



]

export const defaultSentences = [
  "Hello, how are you today?",
  "The weather is beautiful outside.",
  "I love to read books in the evening.",
  "Can you help me with this problem?",
  "The cat is sleeping on the sofa.",
  "We need to go to the store later.",
  "This movie is really interesting.",
  "Please turn off the lights when you leave.",
  "The food smells delicious from the kitchen.",
  "I'm excited about the upcoming vacation.",
  "She likes to drink coffee in the morning.",
  "He plays the guitar very well.",
  "They are planning a trip to the mountains.",
  "The dog is barking loudly.",
  "We had a great time at the party.",
  "The sun rises in the east.",
  "She wears a beautiful dress.",
  "He is learning to code in Python.",
  "They visited their grandparents last weekend.",
  "The car broke down on the way to work.",
  "I need to finish my homework.",
  "She walks to school every day.",
  "He is a very kind person.",
  "They built a new house.",
  "The birds are singing outside.",
  "We are going to have dinner soon.",
  "This is a difficult question.",
  "Please close the door quietly.",
  "The children are playing in the park.",
  "I bought some fresh vegetables.",
  "She speaks three languages fluently.",
  "He teaches mathematics at the university.",
  "They watch movies every Friday night.",
  "The train arrives at six o'clock.",
  "We will meet at the cafe.",
  "This book has many colorful pictures.",
  "He is good at playing chess.",
  "They often go for a walk in the evening.",
  "The flowers smell sweet.",
  "I enjoy listening to music.",
  "She drives an old car.",
  "He runs every morning for exercise.",
  "They went swimming in the lake.",
  "The baby is sleeping soundly.",
  "We should clean the house.",
  "This is a very comfortable chair.",
  "Please remember to lock the door.",
  "The moon is full tonight.",
  "I like to cook Italian food.",
  "She paints beautiful landscapes.",
  "He writes interesting stories.",
  "They are having a picnic tomorrow.",
  "The computer is running slow.",
  "We need to buy new furniture.",
  "This song makes me happy.",
  "Please don't forget your keys.",
  "The doctor advised him to rest.",
  "I woke up early today.",
  "She has a great sense of humor.",
  "The ocean is vast and mysterious.",
  "Learning new things is always exciting.",
  "My favorite color is blue.",
  "We celebrated her birthday yesterday.",
  "He enjoys hiking in nature.",
  "The news report was very informative.",
  "Can you pass me the salt, please?",
  "The concert was absolutely amazing.",
  "It's important to stay hydrated.",
  "She's wearing a warm winter coat.",
  "The garden is full of beautiful roses.",
  "I usually eat breakfast at seven.",
  "He fixed the broken window.",
  "They are discussing their future plans.",
  "The show starts in ten minutes.",
  "We need to protect the environment.",
  "This soup tastes incredibly good.",
  "Please arrive on time for the meeting.",
  "The old bridge needs repair.",
  "I'm looking forward to the weekend.",
  "She takes excellent photographs.",
  "He works hard to achieve his goals.",
  "They are visiting historical sites.",
  "The rain made the streets slippery.",
  "We went camping in the forest.",
  "This puzzle is quite challenging.",
  "Don't forget to send that email.",
  "The sun sets in the west.",
  "I prefer tea over coffee.",
  "She has a very busy schedule.",
  "He rides his bicycle to work.",
  "They volunteer at the local shelter.",
  "The traffic was heavy this morning.",
  "We had a picnic by the river.",
  "This painting is a masterpiece.",
  "Please be careful when crossing the street.",
  "The sound of waves is very calming.",
  "I enjoy spending time with my family.",
  "She sings beautifully.",
  "He's a talented musician.",
  "They went on a long road trip.",
  "The little bird built a nest.",
  "We should save money for a rainy day.",
  "This exercise is good for your health.",
  "Please keep the noise down.",
  "The wind is blowing strongly.",
  "I love to watch the stars at night.",
  "She writes poetry in her free time.",
  "He helps his neighbors regularly.",
  "They spent the afternoon fishing.",
  "The computer crashed unexpectedly.",
  "We planted new trees in the yard.",
  "This is a very difficult decision.",
  "Please remember your passport.",
  "The chef prepared a delicious meal.",
  "I finished reading that novel.",
  "She has a beautiful smile.",
  "He learns quickly.",
  "They often go for walks on the beach.",
  "The ancient ruins are fascinating.",
  "We should organize our files.",
  "This recipe is easy to follow.",
  "Please turn down the volume.",
  "The cat is chasing a mouse.",
  "I love the smell of fresh bread.",
  "She studies history at college.",
  "He plays basketball professionally.",
  "They explored the cave.",
  "The silence in the library was profound.",
  "We took a boat ride on the lake.",
  "This documentary is very insightful.",
  "Please close the window, it's cold.",
  "The old house has a mysterious aura.",
  "I enjoy listening to podcasts.",
  "She dreams of traveling the world.",
  "He builds model airplanes.",
  "They are passionate about charity work.",
  "The performance received a standing ovation.",
  "We need to conserve water.",
  "This jacket is waterproof.",
  "Please wipe your feet.",
  "The ice cream melted quickly.",
  "I like to draw in my sketchbook.",
  "She teaches yoga classes.",
  "He fixes cars for a living.",
  "They sailed across the ocean.",
  "The aroma of coffee filled the air.",
  "We went to an art exhibition.",
  "This film won several awards.",
  "Please pick up your toys.",
  "The mountain peaks are covered in snow.",
  "I enjoy a good cup of tea.",
  "She practices piano every day.",
  "He is a talented storyteller.",
  "They celebrated their anniversary.",
  "The clock struck midnight.",
  "We need to prepare for the storm.",
  "This material is very durable.",
  "Please forgive me.",
  "The city lights are beautiful at night."
];