export const foodIcons = {
    "Apple": "🍎",
    "Banana": "🍌",
    "Bread": "🍞",
    "Cheese": "🧀",
    "Chicken": "🍗",
    "Rice": "🍚",
    "Pasta": "🍝",
    "Egg": "🥚",
    "Milk": "🥛",
    "Fish": "🐟",
    "Carrot": "🥕",
    "Potato": "🥔",
    "Tomato": "🍅",
    "Broccoli": "🥦",
    "Onion": "🧅",
    "Garlic": "🧄",
    "Orange": "🍊",
    "Grapes": "🍇",
    "Strawberry": "🍓",
    "Watermelon": "🍉",
    "Pizza": "🍕",
    "Hamburger": "🍔",
    "Hot Dog": "🌭",
    "French Fries": "🍟",
    "Salad": "🥗",
    "Soup": "🥣",
    "Sandwich": "🥪",
    "Cake": "🍰",
    "Cookie": "🍪",
    "Ice Cream": "🍦",
    "Coffee": "☕",
    "Tea": "🍵",
    "Juice": "🍹",
    "Water": "💧",
    "Doughnut": "🍩",
    "Candy": "🍬",
    "Chocolate": "🍫",
    "Popcorn": "🍿",
    "Honey": "🍯",
    "Sugar": "🍚",
    "Salt": "🧂",
    "Pepper": "🌶️",
    "Oil": "🍾",
    "Vinegar": "🍾",
    "Butter": "🧈",
    "Jam": "🍓",
    "Yogurt": "🍦",
    "Cereal": "🥣",
    "Pancake": "🥞",
    "Sausage": "🌭",
};
export  const animalIcons = {
    "Dog": "🐶",
    "Cat": "🐱",
    "Lion": "🦁",
    "Elephant": "🐘",
    "Tiger": "🐯",
    "Horse": "🐎",
    "Bird": "🐦",
    "Fish": "🐟",
    "Rabbit": "🐰",
    "Chicken": "🐔",
    "Wolf": "🐺",
    "Monkey": "🐵",
    "Bear": "🐻",
    "Dolphin": "🐬",
    "Shark": "🦈",
    "Cow": "🐄",
    "Pig": "🐷",
    "Sheep": "🐑",
    "Goat": "🐐",
    "Deer": "🦌",
    "Fox": "🦊",
    "Panda": "🐼",
    "Penguin": "🐧",
    "Giraffe": "🦒",
    "Zebra": "🦓",
    "Kangaroo": "🦘",
    "Owl": "🦉",
    "Duck": "🦆",
    "Snake": "🐍",
    "Crocodile": "🐊",
    "Turtle": "🐢",
    "Frog": "🐸",
    "Lizard": "🦎",
    "Spider": "🕷️",
    "Bee": "🐝",
    "Ant": "🐜",
    "Butterfly": "🦋",
    "Whale": "🐳",
    "Octopus": "🐙",
    "Crab": "🦀",
    "Lobster": "🦞",
    "Shrimp": "🦐",
    "Pigeon": "🕊️",
    "Eagle": "🦅",
    "Flamingo": "🦩",
    "Rhino": "🦏",
    "Hippo": "🦛",
    "Snail": "🐌",
    "Hedgehog": "🦔",
    "Squirrel": "🐿️",
    "Otter": "🦦",
    "Raccoon": "🦝",
    "Bat": "🦇"
  };

  export  const itemIcons = {
    ...foodIcons,
    ...animalIcons
};
  export const animals = [
    { name: "Dog", icon: "🐶" },
    { name: "Cat", icon: "🐱" },
    { name: "Lion", icon: "🦁" },
    { name: "Elephant", icon: "🐘" },
    { name: "Tiger", icon: "🐯" },
    { name: "Horse", icon: "🐎" },
    { name: "Bird", icon: "🐦" },
    { name: "Fish", icon: "🐟" },
    { name: "Rabbit", icon: "🐰" },
    { name: "Chicken", icon: "🐔" },
    { name: "Wolf", icon: "🐺" },
    { name: "Monkey", icon: "🐵" },
    { name: "Bear", icon: "🐻" },
    { name: "Dolphin", icon: "🐬" },
    { name: "Shark", icon: "🦈" },
    { name: "Cow", icon: "🐄" },
    { name: "Pig", icon: "🐷" },
    { name: "Sheep", icon: "🐑" },
    { name: "Goat", icon: "🐐" },
    { name: "Deer", icon: "🦌" },
    { name: "Fox", icon: "🦊" },
    { name: "Panda", icon: "🐼" },
    { name: "Penguin", icon: "🐧" },
    { name: "Giraffe", icon: "🦒" },
    { name: "Zebra", icon: "🦓" },
    { name: "Kangaroo", icon: "🦘" },
    { name: "Owl", icon: "🦉" },
    { name: "Duck", icon: "🦆" },
    { name: "Snake", icon: "🐍" },
    { name: "Crocodile", icon: "🐊" },
    { name: "Turtle", icon: "🐢" },
    { name: "Frog", icon: "🐸" },
    { name: "Lizard", icon: "🦎" },
    { name: "Spider", icon: "🕷️" },
    { name: "Bee", icon: "🐝" },
    { name: "Ant", icon: "🐜" },
    { name: "Butterfly", icon: "🦋" },
    { name: "Whale", icon: "🐳" },
    { name: "Octopus", icon: "🐙" },
    { name: "Crab", icon: "🦀" },
    { name: "Lobster", icon: "🦞" },
    { name: "Shrimp", icon: "🦐" },
    { name: "Pigeon", icon: "🕊️" },
    { name: "Eagle", icon: "🦅" },
    { name: "Flamingo", icon: "🦩" },
    { name: "Rhino", icon: "🦏" },
    { name: "Hippo", icon: "🦛" },
    { name: "Snail", icon: "🐌" },
    { name: "Hedgehog", icon: "🦔" },
    { name: "Squirrel", icon: "🐿️" },
    { name: "Otter", icon: "🦦" },
    { name: "Raccoon", icon: "🦝" },
    { name: "Bat", icon: "🦇" },
];

 export const foodItems = [
    { name: "Apple", icon: "🍎" },
    { name: "Banana", icon: "🍌" },
    { name: "Bread", icon: "🍞" },
    { name: "Cheese", icon: "🧀" },
    { name: "Chicken", icon: "🍗" },
    { name: "Rice", icon: "🍚" },
    { name: "Pasta", icon: "🍝" },
    { name: "Egg", icon: "🥚" },
    { name: "Milk", icon: "🥛" },
    { name: "Fish", icon: "🐟" },
    { name: "Carrot", icon: "🥕" },
    { name: "Potato", icon: "🥔" },
    { name: "Tomato", icon: "🍅" },
    { name: "Broccoli", icon: "🥦" },
    { name: "Onion", icon: "🧅" },
    { name: "Garlic", icon: "🧄" },
    { name: "Orange", icon: "🍊" },
    { name: "Grapes", icon: "🍇" },
    { name: "Strawberry", icon: "🍓" },
    { name: "Watermelon", icon: "🍉" },
    { name: "Pizza", icon: "🍕" },
    { name: "Hamburger", icon: "🍔" },
    { name: "Hot Dog", icon: "🌭" },
    { name: "French Fries", icon: "🍟" },
    { name: "Salad", icon: "🥗" },
    { name: "Soup", icon: "🥣" },
    { name: "Sandwich", icon: "🥪" },
    { name: "Cake", icon: "🍰" },
    { name: "Cookie", icon: "🍪" },
    { name: "Ice Cream", icon: "🍦" },
    { name: "Coffee", icon: "☕" },
    { name: "Tea", icon: "🍵" },
    { name: "Juice", icon: "🍹" },
    { name: "Water", icon: "💧" },
    { name: "Doughnut", icon: "🍩" },
    { name: "Candy", icon: "🍬" },
    { name: "Chocolate", icon: "🍫" },
    { name: "Popcorn", icon: "🍿" },
    { name: "Honey", icon: "🍯" },
    { name: "Sugar", icon: "🍚" }, // Reusing rice icon for sugar, or can find a better one
    { name: "Salt", icon: "🧂" },
    { name: "Pepper", icon: "🌶️" }, // Reusing pepper icon for spice, or can find a better one
    { name: "Oil", icon: "🍾" }, // Reusing bottle icon for oil, or can find a better one
    { name: "Vinegar", icon: "🍾" }, // Reusing bottle icon for vinegar
    { name: "Butter", icon: "🧈" },
    { name: "Jam", icon: "🍓" }, // Reusing strawberry icon for jam
    { name: "Yogurt", icon: "🍦" }, // Reusing ice cream icon for yogurt
    { name: "Cereal", icon: "🥣" }, // Reusing bowl icon for cereal
    { name: "Pancake", icon: "🥞" },
    { name: "Sausage", icon: "🌭" }, // Reusing hot dog icon for sausage
];