export const words =
    [{  en: "Succeed",  he: "להצליח" },
    {  en: "Suffer",  he: "לסבול" },
    {  en: "Suggest",  he: "להציע" },
    {  en: "Suit",  he: "להתאים" },
    {  en: "Summarize",  he: "לסכם" },
    {  en: "Supervise",  he: "לפקח" },
    {  en: "Supplement",  he: "להשלים" },
    {  en: "Supply",  he: "לספק" },
    {  en: "Support",  he: "לתמוך" },
    {  en: "Suppose",  he: "להניח" },
    {  en: "Suppress",  he: "לדכא" },
    {  en: "Sure",  he: "לוודא / להיות בטוח" },
    {  en: "Surface",  he: "לצוף / לעלות על פני השטח" },
    {  en: "Surge",  he: "לזנק / להתפרץ" },
    {  en: "Surmise",  he: "לשער" },
    {  en: "Surpass",  he: "לעבור / להתעלות על" },
    {  en: "Surprise",  he: "להפתיע" },
    {  en: "Surrender",  he: "להיכנע" },
    {  en: "Surround",  he: "להקיף" },
    {  en: "Survey",  he: "לסקור / למדוד" },
    {  en: "Survive",  he: "לשרוד" },
    {  en: "Suspect",  he: "לחשוד" },
    {  en: "Suspend",  he: "להשעות / לתלות" },
    {  en: "Sustain",  he: "לקיים / לשמר" },
    {  en: "Swear",  he: "להישבע / לקלל" },
    {  en: "Sweep",  he: "לטאטא" },
    {  en: "Swell",  he: "להתנפח" },
    {  en: "Swim",  he: "לשחות" },
    {  en: "Swing",  he: "להתנדנד" },
    {  en: "Switch",  he: "להחליף" },
    {  en: "Symbolize",  he: "לסמל" },
    {  en: "Sympathize",  he: "להזדהות" },
    {  en: "Synchronize",  he: "לסנכרן" },
    {  en: "Synthesize",  he: "לסנתז" },
    {  en: "Systematize",  he: "לסדר / למיין" },
    {  en: "Table",  he: "להגיש הצעה (בדיון)" },
    {  en: "Tackle",  he: "לטפל ב-" },
    {  en: "Tag",  he: "לתייג" },
    {  en: "Take",  he: "לקחת" },
    {  en: "Talk",  he: "לדבר" },
    {  en: "Tame",  he: "לאלף" },
    {  en: "Tap",  he: "להקיש / לפתוח ברז" },
    {  en: "Target",  he: "למקד" },
    {  en: "Taste",  he: "לטעום" },
    {  en: "Tax",  he: "למסות" },
    {  en: "Teach",  he: "ללמד" },
    {  en: "Team",  he: "לשתף פעולה" },
    {  en: "Tear",  he: "לקרוע" },
    {  en: "Split",  he: "לפצל" },
    {  en: "Sponsor",  he: "לתת חסות" },
    {  en: "Spot",  he: "לאתר / לזהות" },
    {  en: "Spread",  he: "לפרוש / להתפשט" },
    {  en: "Spring",  he: "לקפוץ / לנבוע" },
    {  en: "Sprout",  he: "לנבוט" },
    {  en: "Squeeze",  he: "לסחוט / ללחוץ" },
    {  en: "Stab",  he: "לדקור" },
    {  en: "Stabilize",  he: "לייצב" },
    {  en: "Stack",  he: "לערום" },
    {  en: "Staff",  he: "לאייש" },
    {  en: "Stain",  he: "להכתים" },
    {  en: "Stamp",  he: "להחתים / לדרוך" },
    {  en: "Stand",  he: "לעמוד" },
    {  en: "Star",  he: "לככב" },
    {  en: "Stare",  he: "לבהות" },
    {  en: "Start",  he: "להתחיל" },
    {  en: "Starve",  he: "להרעיב / לגווע ברעב" },
    {  en: "State",  he: "להצהיר" },
    {  en: "Station",  he: "להציב / למקם" },
    {  en: "Stay",  he: "להישאר" },
    {  en: "Steal",  he: "לגנוב" },
    {  en: "Steer",  he: "לנווט / לכוון" },
    {  en: "Step",  he: "לפסוע / לצעוד" },
    {  en: "Stick",  he: "להדביק / להידבק" },
    {  en: "Stiffen",  he: "להקשיח / להתקשות" },
    {  en: "Stimulate",  he: "לגרות / לעורר" },
    {  en: "Stir",  he: "לערבב / לעורר" },
    {  en: "Stop",  he: "לעצור" },
    {  en: "Store",  he: "לאחסן" },
    {  en: "Straighten",  he: "ליישר" },
    {  en: "Strain",  he: "למתוח / לאמץ" },
    {  en: "Strap",  he: "לקשור ברצועה" },
    {  en: "Stream",  he: "לזרום" },
    {  en: "Strengthen",  he: "לחזק" },
    {  en: "Stress",  he: "להדגיש / להלחיץ" },
    {  en: "Stretch",  he: "למתוח" },
    {  en: "Strike",  he: "להכות / לשבות" },
    {  en: "String",  he: "להשחיל" },
    {  en: "Strip",  he: "להפשיט / לקלף" },
    {  en: "Strive",  he: "לשאוף / להתאמץ" },
    {  en: "Structure",  he: "לבנות / לארגן" },
    {  en: "Struggle",  he: "להיאבק" },
    {  en: "Study",  he: "ללמוד" },
    {  en: "Stuff",  he: "לדחוס / למלא" },
    {  en: "Submit",  he: "להגיש / להיכנע" },
    {  en: "Subscribe",  he: "להירשם כמנוי" },
    {  en: "Subsidize",  he: "לסבסד" },
    {  en: "Substitute",  he: "להחליף" },
    {  en: "Shout",  he: "לצעוק" },
    {  en: "Show",  he: "להראות" },
    {  en: "Shrink",  he: "להתכווץ" },
    {  en: "Shut",  he: "לסגור" },
    {  en: "Sigh",  he: "לנשום אנחה" },
    {  en: "Sight",  he: "לראות / להבחין" },
    {  en: "Sign",  he: "לחתום / לאותת" },
    {  en: "Signal",  he: "לאותת" },
    {  en: "Signify",  he: "לציין / לסמל" },
    {  en: "Silence",  he: "להשתיק" },
    {  en: "Simplify",  he: "לפשט" },
    {  en: "Simulate",  he: "לדמות" },
    {  en: "Sing",  he: "לשיר" },
    {  en: "Sink",  he: "לשקוע" },
    {  en: "Sit",  he: "לשבת" },
    {  en: "Ski",  he: "לגלוש בסקי" },
    {  en: "Skip",  he: "לדלג" },
    {  en: "Slap",  he: "לסטור" },
    {  en: "Sleep",  he: "לישון" },
    {  en: "Slice",  he: "לחתוך לפרוסות" },
    {  en: "Slide",  he: "להחליק" },
    {  en: "Slip",  he: "להחליק / למעוד" },
    {  en: "Slope",  he: "לנטות / להשתפל" },
    {  en: "Slow",  he: "להאט" },
    {  en: "Smash",  he: "לנפץ" },
    {  en: "Smell",  he: "להריח" },
    {  en: "Smile",  he: "לחייך" },
    {  en: "Smoke",  he: "לעשן" },
    {  en: "Smooth",  he: "להחליק / להחליק" },
    {  en: "Snatch",  he: "לחטוף" },
    {  en: "Sneeze",  he: "להתעטש" },
    {  en: "Sniff",  he: "להריח / לרחרח" },
    {  en: "Soak",  he: "להשרות" },
    {  en: "Sober",  he: "לפכח / להתפכח" },
    {  en: "Soften",  he: "לרכך" },
    {  en: "Solve",  he: "לפתור" },
    {  en: "Sort",  he: "למיין" },
    {  en: "Sound",  he: "להישמע" },
    {  en: "Source",  he: "למצוא מקור" },
    {  en: "Spare",  he: "לחסוך / לוותר" },
    {  en: "Spark",  he: "לעורר / לגרור ניצוץ" },
    {  en: "Speak",  he: "לדבר" },
    {  en: "Specialize",  he: "להתמחות" },
    {  en: "Specify",  he: "לפרט / לציין במדויק" },
    {  en: "Speculate",  he: "לשער" },
    {  en: "Speed",  he: "להאיץ" },
    {  en: "Spell",  he: "לאיית" },
    {  en: "Spend",  he: "להוציא (כסף) / לבלות (זמן)" },
    {  en: "Spin",  he: "לסובב" },
    {  en: "Rule",  he: "לשלוט / לפקוד" },
    {  en: "Run",  he: "לרוץ / לנהל" },
    {  en: "Rush",  he: "למהר / להאיץ" },
    {  en: "Sacrifice",  he: "להקריב" },
    {  en: "Sail",  he: "להפליג" },
    {  en: "Salute",  he: "להצדיע" },
    {  en: "Sanction",  he: "לאשר / להטיל סנקציה" },
    {  en: "Satisfy",  he: "לספק" },
    {  en: "Save",  he: "להציל / לחסוך" },
    {  en: "Say",  he: "להגיד" },
    {  en: "Scale",  he: "למדוד / לטפס" },
    {  en: "Scan",  he: "לסרוק" },
    {  en: "Scare",  he: "להפחיד" },
    {  en: "Scatter",  he: "לפזר" },
    {  en: "Schedule",  he: "לתזמן" },
    {  en: "Scheme",  he: "לתכנן מזימה" },
    {  en: "Scold",  he: "לנזוף" },
    {  en: "Score",  he: "לקלוע / להשיג" },
    {  en: "Scratch",  he: "לגרד" },
    {  en: "Scream",  he: "לצרוח" },
    {  en: "Screen",  he: "לסנן / להקרין" },
    {  en: "Seal",  he: "לאטום / לחתום" },
    {  en: "Search",  he: "לחפש" },
    {  en: "Seat",  he: "להושיב" },
    {  en: "Secure",  he: "לאבטח / להבטיח" },
    {  en: "See",  he: "לראות" },
    {  en: "Seek",  he: "לחפש" },
    {  en: "Seem",  he: "להיראות" },
    {  en: "Seize",  he: "לתפוס / לתפוס בכוח" },
    {  en: "Select",  he: "לבחור" },
    {  en: "Sell",  he: "למכור" },
    {  en: "Send",  he: "לשלוח" },
    {  en: "Sense",  he: "להרגיש / לחוש" },
    {  en: "Separate",  he: "להפריד" },
    {  en: "Serve",  he: "לשרת / להגיש" },
    {  en: "Set",  he: "לקבוע / להגדיר" },
    {  en: "Settle",  he: "להתיישב / ליישב" },
    {  en: "Sever",  he: "לבתר / לנתק" },
    {  en: "Shake",  he: "לנער" },
    {  en: "Shape",  he: "לעצב" },
    {  en: "Share",  he: "לשתף" },
    {  en: "Shed",  he: "להשיל / לפזר" },
    {  en: "Shelter",  he: "לחסות / לתת מחסה" },
    {  en: "Shift",  he: "להזיז / להעביר" },
    {  en: "Shine",  he: "לזהור" },
    {  en: "Ship",  he: "לשלוח (בספינה/משלוח)" },
    {  en: "Shock",  he: "להלם" },
    {  en: "Shoot",  he: "לירות" },
    {  en: "Shop",  he: "לקנות" },
    {  en: "Shorten",  he: "לקצר" },
    {  en: "Represent",  he: "לייצג" },
    {  en: "Reprimand",  he: "לגעור / לנזוף" },
    {  en: "Reproduce",  he: "לשכפל / להתרבות" },
    {  en: "Request",  he: "לבקש" },
    {  en: "Require",  he: "לדרוש" },
    {  en: "Rescue",  he: "להציל" },
    {  en: "Research",  he: "לחקור" },
    {  en: "Resemble",  he: "להידמות ל-" },
    {  en: "Resent",  he: "להתרעם" },
    {  en: "Reside",  he: "לגור / להתגורר" },
    {  en: "Resign",  he: "להתפטר" },
    {  en: "Resist",  he: "להתנגד" },
    {  en: "Resolve",  he: "לפתור / להחליט" },
    {  en: "Resort",  he: "לנקוט ב- / להיזקק ל-" },
    {  en: "Respect",  he: "לכבד" },
    {  en: "Respond",  he: "להגיב" },
    {  en: "Rest",  he: "לנוח" },
    {  en: "Restore",  he: "לשחזר / להחזיר" },
    {  en: "Restrain",  he: "לרסן" },
    {  en: "Restrict",  he: "להגביל" },
    {  en: "Result",  he: "לגרום ל-" },
    {  en: "Resume",  he: "להמשיך / לחדש" },
    {  en: "Retain",  he: "לשמור / להחזיק" },
    {  en: "Retreat",  he: "לסגת" },
    {  en: "Retrieve",  he: "לאחזר" },
    {  en: "Return",  he: "לחזור / להחזיר" },
    {  en: "Reveal",  he: "לחשוף" },
    {  en: "Revenge",  he: "לנקום" },
    {  en: "Reverse",  he: "להפוך / לבטל" },
    {  en: "Review",  he: "לסקור" },
    {  en: "Revise",  he: "לשנות / לתקן" },
    {  en: "Revive",  he: "להחיות" },
    {  en: "Revolt",  he: "למרוד" },
    {  en: "Reward",  he: "לתגמל" },
    {  en: "Rid",  he: "לשחרר מ-" },
    {  en: "Ride",  he: "לרכוב" },
    {  en: "Ridicule",  he: "ללעוג" },
    {  en: "Right",  he: "ליישר / לתקן" },
    {  en: "Rise",  he: "לעלות" },
    {  en: "Risk",  he: "לסכן" },
    {  en: "Roam",  he: "לשוטט" },
    {  en: "Roar",  he: "לשאוג" },
    {  en: "Roast",  he: "לצלות" },
    {  en: "Rob",  he: "לשדוד" },
    {  en: "Rock",  he: "להתנדנד / לנדנד" },
    {  en: "Roll",  he: "לגלגל" },
    {  en: "Rotate",  he: "לסובב" },
    {  en: "Rough",  he: "לגרום לחיספוס" },
    {  en: "Round",  he: "לעגל" },
    {  en: "Ruin",  he: "להרוס" },
    {  en: "Recommend",  he: "להמליץ" },
    {  en: "Reconcile",  he: "לפייס / ליישב" },
    {  en: "Reconstruct",  he: "לשחזר / לבנות מחדש" },
    {  en: "Record",  he: "להקליט / לתעד" },
    {  en: "Recover",  he: "להחלים / לשחזר" },
    {  en: "Recrease",  he: "להפחית (שוב)" },
    {  en: "Recruit",  he: "לגייס" },
    {  en: "Rectify",  he: "לתקן" },
    {  en: "Recur",  he: "לחזור ולהתרחש" },
    {  en: "Reduce",  he: "להפחית" },
    {  en: "Refer",  he: "להפנות / להתייחס" },
    {  en: "Refine",  he: "לזקק / לשפר" },
    {  en: "Reflect",  he: "לשקף / להרהר" },
    {  en: "Reform",  he: "לתקן / לשנות" },
    {  en: "Refrain",  he: "להימנע מ-" },
    {  en: "Refresh",  he: "לרענן" },
    {  en: "Refund",  he: "להחזיר כסף" },
    {  en: "Refuse",  he: "לסרב" },
    {  en: "Regain",  he: "להשיב / להשיג בחזרה" },
    {  en: "Regard",  he: "להתייחס / להתחשב" },
    {  en: "Register",  he: "לרשום / להירשם" },
    {  en: "Regret",  he: "להצטער" },
    {  en: "Regulate",  he: "לווסת" },
    {  en: "Rehabilitate",  he: "לשקם" },
    {  en: "Reign",  he: "לשלוט (במלוכה)" },
    {  en: "Reinforce",  he: "לחזק" },
    {  en: "Reject",  he: "לדחות" },
    {  en: "Relate",  he: "להתייחס / לקשר" },
    {  en: "Relax",  he: "להירגע" },
    {  en: "Release",  he: "לשחרר" },
    {  en: "Relieve",  he: "להקל" },
    {  en: "Relish",  he: "ליהנות מ-" },
    {  en: "Rely",  he: "להסתמך" },
    {  en: "Remain",  he: "להישאר" },
    {  en: "Remark",  he: "להעיר / לציין" },
    {  en: "Remember",  he: "לזכור" },
    {  en: "Remind",  he: "להזכיר" },
    {  en: "Remit",  he: "לשלוח (כסף) / למחול" },
    {  en: "Remove",  he: "להסיר" },
    {  en: "Render",  he: "להפוך ל- / לתת" },
    {  en: "Renew",  he: "לחדש" },
    {  en: "Renounce",  he: "לוותר על / להתכחש ל-" },
    {  en: "Repair",  he: "לתקן" },
    {  en: "Repay",  he: "להחזיר חוב" },
    {  en: "Repeat",  he: "לחזור" },
    {  en: "Repel",  he: "להדוף / לדחות" },
    {  en: "Replace",  he: "להחליף" },
    {  en: "Replenish",  he: "למלא מחדש" },
    {  en: "Reply",  he: "להשיב" },
    {  en: "Report",  he: "לדווח" },
    {  en: "Progress",  he: "להתקדם" },
    {  en: "Prohibit",  he: "לאסור" },
    {  en: "Project",  he: "להקרין / לתכנן" },
    {  en: "Promise",  he: "להבטיח" },
    {  en: "Promote",  he: "לקדם" },
    {  en: "Prompt",  he: "להניע / לעודד" },
    {  en: "Pronounce",  he: "להגות / להכריז" },
    {  en: "Propose",  he: "להציע" },
    {  en: "Prosecute",  he: "לתבוע (משפטית)" },
    {  en: "Protect",  he: "להגן" },
    {  en: "Protest",  he: "למחות" },
    {  en: "Prove",  he: "להוכיח" },
    {  en: "Provide",  he: "לספק" },
    {  en: "Provoke",  he: "לעורר / להקניט" },
    {  en: "Publish",  he: "לפרסם" },
    {  en: "Pull",  he: "למשוך" },
    {  en: "Pump",  he: "לשאוב" },
    {  en: "Punch",  he: "להכות באגרוף" },
    {  en: "Punish",  he: "להעניש" },
    {  en: "Purchase",  he: "לרכוש" },
    {  en: "Pursue",  he: "לרדוף / לשאוף" },
    {  en: "Push",  he: "לדחוף" },
    {  en: "Put",  he: "לשים" },
    {  en: "Qualify",  he: "להכשיר / להסמיך" },
    {  en: "Quantify",  he: "לכמת" },
    {  en: "Question",  he: "לשאול / להטיל ספק" },
    {  en: "Queue",  he: "לעמוד בתור" },
    {  en: "Quit",  he: "להפסיק / לעזוב" },
    {  en: "Race",  he: "לרוץ / להתחרות" },
    {  en: "Radiate",  he: "להקרין" },
    {  en: "Raise",  he: "להרים / לגדל" },
    {  en: "Rally",  he: "להתכנס / לאסוף כוחות" },
    {  en: "Randomize",  he: "לאקראי" },
    {  en: "Range",  he: "לנוע בטווח" },
    {  en: "Rank",  he: "לדרג" },
    {  en: "Rate",  he: "לדרג / להעריך" },
    {  en: "Reach",  he: "להגיע" },
    {  en: "React",  he: "להגיב" },
    {  en: "Read",  he: "לקרוא" },
    {  en: "Realize",  he: "להבין / להכיר ב-" },
    {  en: "Reap",  he: "לקצור (תגמולים)" },
    {  en: "Rear",  he: "לגדל (ילדים / בעלי חיים)" },
    {  en: "Reason",  he: "להתדיין / להסיק" },
    {  en: "Reassure",  he: "להרגיע" },
    {  en: "Rebel",  he: "למרוד" },
    {  en: "Recall",  he: "להיזכר / לבטל" },
    {  en: "Receive",  he: "לקבל" },
    {  en: "Recite",  he: "לדקלם" },
    {  en: "Recognize",  he: "לזהות" },
    {  en: "Pinch",  he: "לצבוט" },
    {  en: "Pine",  he: "להשתוקק" },
    {  en: "Pioneer",  he: "להיות חלוץ / לפרוץ דרך" },
    {  en: "Place",  he: "להניח / למקם" },
    {  en: "Plan",  he: "לתכנן" },
    {  en: "Plant",  he: "לשתול" },
    {  en: "Play",  he: "לשחק" },
    {  en: "Plead",  he: "להתחנן / לטעון (בבית משפט)" },
    {  en: "Please",  he: "לרצות / לשמח" },
    {  en: "Pledge",  he: "להתחייב / להבטיח" },
    {  en: "Plot",  he: "לתכנן מזימה / לשרטט" },
    {  en: "Plunge",  he: "לצלול / לצנוח" },
    {  en: "Point",  he: "להצביע / לציין" },
    {  en: "Poison",  he: "להרעיל" },
    {  en: "Police",  he: "לפקח / לאכוף" },
    {  en: "Pollute",  he: "לזהם" },
    {  en: "Ponder",  he: "להרהר" },
    {  en: "Pop",  he: "לקפוץ / להתפוצץ" },
    {  en: "Portray",  he: "לתאר / לצייר" },
    {  en: "Pose",  he: "להציב / להוות" },
    {  en: "Position",  he: "למקם" },
    {  en: "Possess",  he: "להחזיק ב-" },
    {  en: "Post",  he: "לפרסם / לשלוח בדואר" },
    {  en: "Postpone",  he: "לדחות" },
    {  en: "Pour",  he: "למזוג" },
    {  en: "Practice",  he: "לתרגל" },
    {  en: "Praise",  he: "לשבח" },
    {  en: "Pray",  he: "להתפלל" },
    {  en: "Precede",  he: "להקדים" },
    {  en: "Precipitate",  he: "לזרז / לשקוע" },
    {  en: "Predict",  he: "לחזות" },
    {  en: "Prefer",  he: "להעדיף" },
    {  en: "Prepare",  he: "להכין" },
    {  en: "Prescribe",  he: "לרשום (תרופה / הוראות)" },
    {  en: "Present",  he: "להציג" },
    {  en: "Preserve",  he: "לשמר" },
    {  en: "Preside",  he: "לנהל ישיבה" },
    {  en: "Press",  he: "ללחוץ" },
    {  en: "Presume",  he: "להניח" },
    {  en: "Pretend",  he: "להעמיד פנים" },
    {  en: "Prevail",  he: "לגבור / לנצח" },
    {  en: "Prevent",  he: "למנוע" },
    {  en: "Print",  he: "להדפיס" },
    {  en: "Proceed",  he: "להמשיך" },
    {  en: "Process",  he: "לעבד" },
    {  en: "Proclaim",  he: "להכריז" },
    {  en: "Produce",  he: "לייצר" },
    {  en: "Profess",  he: "להצהיר" },
    {  en: "Program",  he: "לתכנת" },
    {  en: "Optimize",  he: "למטב" },
    {  en: "Order",  he: "להזמין / לפקוד" },
    {  en: "Organize",  he: "לארגן" },
    {  en: "Orient",  he: "לכוון / להתמצא" },
    {  en: "Originate",  he: "לנבוע / ליזום" },
    {  en: "Outline",  he: "לתאר בקווים כלליים" },
    {  en: "Outperform",  he: "לעלות בביצועים" },
    {  en: "Outweigh",  he: "לעלות בחשיבות / לשקול יותר" },
    {  en: "Overcome",  he: "להתגבר" },
    {  en: "Overlook",  he: "להתעלם מ- / להשקיף על" },
    {  en: "Oversee",  he: "לפקח" },
    {  en: "Overtake",  he: "לעקוף" },
    {  en: "Overthrow",  he: "להפיל / להדיח" },
    {  en: "Owe",  he: "להיות חייב" },
    {  en: "Own",  he: "להיות בעלים של" },
    {  en: "Pace",  he: "ללכת בקצב" },
    {  en: "Pack",  he: "לארוז" },
    {  en: "Paddle",  he: "לחתור" },
    {  en: "Paint",  he: "לצבוע" },
    {  en: "Pair",  he: "לזווג" },
    {  en: "Panic",  he: "לפאניקה" },
    {  en: "Parallel",  he: "להקביל" },
    {  en: "Pardon",  he: "לסלוח" },
    {  en: "Park",  he: "להחנות" },
    {  en: "Part",  he: "להפריד" },
    {  en: "Participate",  he: "להשתתף" },
    {  en: "Pass",  he: "לעבור / למסור" },
    {  en: "Pave",  he: "לסלול" },
    {  en: "Pay",  he: "לשלם" },
    {  en: "Peel",  he: "לקלף" },
    {  en: "Peer",  he: "להציץ" },
    {  en: "Penalize",  he: "להעניש" },
    {  en: "Penetrate",  he: "לחדור" },
    {  en: "Perceive",  he: "לתפוס / לקלוט" },
    {  en: "Perform",  he: "לבצע" },
    {  en: "Permit",  he: "להרשות" },
    {  en: "Persist",  he: "להתמיד" },
    {  en: "Personalize",  he: "להתאים אישית" },
    {  en: "Persuade",  he: "לשכנע" },
    {  en: "Pertain",  he: "להיות שייך ל- / להתייחס ל-" },
    {  en: "Petition",  he: "לערוך עצומה / לבקש" },
    {  en: "Phase",  he: "להדרג" },
    {  en: "Phone",  he: "לטלפן" },
    {  en: "Photograph",  he: "לצלם" },
    {  en: "Pick",  he: "לבחור / לקטוף" },
    {  en: "Pile",  he: "לערום" },
    {  en: "Pilot",  he: "להטיס" },
    {  en: "Mend",  he: "לתקן / לאחות" },
    {  en: "Mention",  he: "להזכיר" },
    {  en: "Merge",  he: "למזג" },
    {  en: "Mess",  he: "לבלגן" },
    {  en: "Mind",  he: "לאכפת ל-" },
    {  en: "Minimize",  he: "למזער" },
    {  en: "Mirror",  he: "לשקף" },
    {  en: "Mislead",  he: "להטעות" },
    {  en: "Miss",  he: "להתגעגע / לפספס" },
    {  en: "Mix",  he: "לערבב" },
    {  en: "Model",  he: "לדגמן / ליצור דגם" },
    {  en: "Modify",  he: "לשנות" },
    {  en: "Monitor",  he: "לנטר" },
    {  en: "Motivate",  he: "להניע" },
    {  en: "Mount",  he: "להרכיב / לעלות" },
    {  en: "Mourn",  he: "להתאבל" },
    {  en: "Move",  he: "לזוז / להזיז" },
    {  en: "Multiply",  he: "להכפיל" },
    {  en: "Murder",  he: "לרצוח" },
    {  en: "Mutter",  he: "למלמל" },
    {  en: "Narrate",  he: "לספר / לקריין" },
    {  en: "Narrow",  he: "להצר" },
    {  en: "Navigate",  he: "לנווט" },
    {  en: "Need",  he: "לצרוך / להזדקק" },
    {  en: "Neglect",  he: "להזניח" },
    {  en: "Negotiate",  he: "לנהל משא ומתן" },
    {  en: "Nod",  he: "להנהן" },
    {  en: "Nominate",  he: "למנות / להציע מועמד" },
    {  en: "Note",  he: "לציין / לרשום" },
    {  en: "Notice",  he: "להבחין" },
    {  en: "Notify",  he: "להודיע" },
    {  en: "Nourish",  he: "להזין" },
    {  en: "Nurse",  he: "לטפל ב- / להניק" },
    {  en: "Obey",  he: "לציית" },
    {  en: "Object",  he: "להתנגד" },
    {  en: "Oblige",  he: "לחייב" },
    {  en: "Observe",  he: "להתבונן / לצפות" },
    {  en: "Obtain",  he: "להשיג" },
    {  en: "Occupy",  he: "לתפוס / לכבוש" },
    {  en: "Occur",  he: "להתרחש" },
    {  en: "Offend",  he: "להעליב" },
    {  en: "Offer",  he: "להציע" },
    {  en: "Offset",  he: "לקזז" },
    {  en: "Omit",  he: "להשמיט" },
    {  en: "Open",  he: "לפתוח" },
    {  en: "Operate",  he: "להפעיל / לתפעל" },
    {  en: "Oppose",  he: "להתנגד" },
    {  en: "Leap",  he: "לקפוץ" },
    {  en: "Learn",  he: "ללמוד" },
    {  en: "Leave",  he: "לעזוב" },
    {  en: "Lecture",  he: "להרצות" },
    {  en: "Lend",  he: "להלוות" },
    {  en: "Lengthen",  he: "להאריך" },
    {  en: "Less",  he: "להפחית (כמות)" },
    {  en: "Let",  he: "לתת ל-" },
    {  en: "Level",  he: "ליישר / לרמת" },
    {  en: "Lie",  he: "לשכב / לשקר" },
    {  en: "Lift",  he: "להרים" },
    {  en: "Light",  he: "להאיר" },
    {  en: "Like",  he: "לאהוב / כמו" },
    {  en: "Limit",  he: "להגביל" },
    {  en: "Line",  he: "ליישר / לשרטט קו" },
    {  en: "Linger",  he: "להתמהמה" },
    {  en: "Link",  he: "לקשר" },
    {  en: "Listen",  he: "להקשיב" },
    {  en: "Live",  he: "לחיות" },
    {  en: "Load",  he: "לטעון" },
    {  en: "Locate",  he: "לאתר" },
    {  en: "Lock",  he: "לנעול" },
    {  en: "Log",  he: "לתעד / לרשום" },
    {  en: "Look",  he: "להסתכל" },
    {  en: "Loop",  he: "לולאה / לחזור על" },
    {  en: "Loose",  he: "לשחרר / לרכך" },
    {  en: "Lose",  he: "לאבד" },
    {  en: "Love",  he: "לאהוב" },
    {  en: "Lower",  he: "להוריד" },
    {  en: "Lure",  he: "לפתות" },
    {  en: "Mail",  he: "לשלוח בדואר" },
    {  en: "Maintain",  he: "לתחזק / לשמר" },
    {  en: "Make",  he: "להכין / לעשות" },
    {  en: "Manage",  he: "לנהל" },
    {  en: "Manufacture",  he: "לייצר" },
    {  en: "Map",  he: "למפות" },
    {  en: "March",  he: "לצעוד" },
    {  en: "Mark",  he: "לסמן" },
    {  en: "Market",  he: "לשווק" },
    {  en: "Marry",  he: "להתחתן" },
    {  en: "Master",  he: "לשלוט ב- / להתמחות ב-" },
    {  en: "Match",  he: "להתאים" },
    {  en: "Matter",  he: "להיות חשוב" },
    {  en: "Mature",  he: "להתבגר" },
    {  en: "Maximize",  he: "למקסם" },
    {  en: "Mean",  he: "להתכוון / להיות ממוצע" },
    {  en: "Measure",  he: "למדוד" },
    {  en: "Mediate",  he: "לתווך" },
    {  en: "Melt",  he: "להימס" },
    {  en: "Injure",  he: "לפגוע / לפצוע" },
    {  en: "Innovate",  he: "לחדש" },
    {  en: "Input",  he: "להזין נתונים" },
    {  en: "Inquire",  he: "לשאול / לברר" },
    {  en: "Insert",  he: "להכניס / להחדיר" },
    {  en: "Inspect",  he: "לבחון / לפקח" },
    {  en: "Inspire",  he: "לתת השראה" },
    {  en: "Install",  he: "להתקין" },
    {  en: "Instruct",  he: "להדריך / להורות" },
    {  en: "Insulate",  he: "לבודד" },
    {  en: "Integrate",  he: "לשלב" },
    {  en: "Intend",  he: "להתכוון" },
    {  en: "Intensify",  he: "להגביר / להתעצם" },
    {  en: "Interact",  he: "לקיים אינטראקציה" },
    {  en: "Interpret",  he: "לפרש" },
    {  en: "Intervene",  he: "להתערב" },
    {  en: "Interview",  he: "לראיין" },
    {  en: "Introduce",  he: "להציג / להכיר" },
    {  en: "Invade",  he: "לפלוש" },
    {  en: "Invent",  he: "להמציא" },
    {  en: "Invest",  he: "להשקיע" },
    {  en: "Investigate",  he: "לחקור" },
    {  en: "Invite",  he: "להזמין" },
    {  en: "Involve",  he: "לערב" },
    {  en: "Iron",  he: "לגהץ" },
    {  en: "Irritate",  he: "לגרות / להרגיז" },
    {  en: "Issue",  he: "להוציא / להנפיק" },
    {  en: "Join",  he: "להצטרף" },
    {  en: "Joke",  he: "להתבדח" },
    {  en: "Judge",  he: "לשפוט" },
    {  en: "Jump",  he: "לקפוץ" },
    {  en: "Justify",  he: "להצדיק" },
    {  en: "Keep",  he: "לשמור" },
    {  en: "Kick",  he: "לבעוט" },
    {  en: "Kill",  he: "להרוג" },
    {  en: "Kiss",  he: "לנשק" },
    {  en: "Kneel",  he: "לכרע ברך" },
    {  en: "Knock",  he: "לדפוק" },
    {  en: "Know",  he: "לדעת" },
    {  en: "Label",  he: "לתייג" },
    {  en: "Lack",  he: "לחסור" },
    {  en: "Land",  he: "לנחות" },
    {  en: "Last",  he: "להימשך / לאחרון" },
    {  en: "Laugh",  he: "לצחוק" },
    {  en: "Launch",  he: "להשיק" },
    {  en: "Lead",  he: "להוביל" },
    {  en: "Leak",  he: "לדלוף" },
    {  en: "Lean",  he: "להישען" },
    {  en: "Head",  he: "לעלות לכיוון / לעמוד בראש" },
    {  en: "Heal",  he: "לרפא / להחלים" },
    {  en: "Hear",  he: "לשמוע" },
    {  en: "Heat",  he: "לחמם" },
    {  en: "Help",  he: "לעזור" },
    {  en: "Hesitate",  he: "להסס" },
    {  en: "Hide",  he: "להתחבא / להחביא" },
    {  en: "Highlight",  he: "להדגיש" },
    {  en: "Hinder",  he: "לעכב / להפריע" },
    {  en: "Hire",  he: "לשכור" },
    {  en: "Hit",  he: "להכות / לפגוע" },
    {  en: "Hold",  he: "להחזיק" },
    {  en: "Honor",  he: "לכבד" },
    {  en: "Hope",  he: "לקוות" },
    {  en: "Host",  he: "לארח" },
    {  en: "House",  he: "לאכסן / לשכן" },
    {  en: "Hunt",  he: "לצוד" },
    {  en: "Hurry",  he: "למהר" },
    {  en: "Hurt",  he: "לפגוע / לכאוב" },
    {  en: "Identify",  he: "לזהות" },
    {  en: "Ignore",  he: "להתעלם" },
    {  en: "Illuminate",  he: "להאיר" },
    {  en: "Illustrate",  he: "להמחיש" },
    {  en: "Imagine",  he: "לדמיין" },
    {  en: "Imitate",  he: "לחקות" },
    {  en: "Impact",  he: "להשפיע" },
    {  en: "Impair",  he: "לפגוע / להחליש" },
    {  en: "Implant",  he: "להשתיל" },
    {  en: "Implement",  he: "ליישם" },
    {  en: "Imply",  he: "לרמוז" },
    {  en: "Import",  he: "לייבא" },
    {  en: "Impose",  he: "להטיל" },
    {  en: "Impress",  he: "להרשים" },
    {  en: "Improve",  he: "לשפר" },
    {  en: "Incline",  he: "לנטות / להטות" },
    {  en: "Include",  he: "לכלול" },
    {  en: "Incorporate",  he: "לשלב / לאגד" },
    {  en: "Increase",  he: "להגדיל" },
    {  en: "Incur",  he: "לגרום ל- (הוצאות, נזקים)" },
    {  en: "Indicate",  he: "לציין" },
    {  en: "Induce",  he: "לגרום / לשדל" },
    {  en: "Indulge",  he: "להתפנק / להתמכר" },
    {  en: "Infect",  he: "להדביק" },
    {  en: "Infer",  he: "להסיק" },
    {  en: "Inflate",  he: "לנפח" },
    {  en: "Influence",  he: "להשפיע" },
    {  en: "Inform",  he: "להודיע" },
    {  en: "Infringe",  he: "להפר" },
    {  en: "Initiate",  he: "ליזום" },
    {  en: "Inject",  he: "להזריק" },
    {  en: "Forecast",  he: "לחזות" },
    {  en: "Forgive",  he: "לסלוח" },
    {  en: "Form",  he: "ליצור / לעצב" },
    {  en: "Formalize",  he: "להפוך לרשמי" },
    {  en: "Formulate",  he: "לנסח" },
    {  en: "Foster",  he: "לטפח" },
    {  en: "Found",  he: "לייסד" },
    {  en: "Frame",  he: "למסגר" },
    {  en: "Free",  he: "לשחרר" },
    {  en: "Freeze",  he: "להקפיא" },
    {  en: "Frighten",  he: "להפחיד" },
    {  en: "Frown",  he: "לקמט מצח" },
    {  en: "Frustrate",  he: "לתסכל" },
    {  en: "Fulfill",  he: "להגשים / למלא" },
    {  en: "Function",  he: "לתפקד" },
    {  en: "Fund",  he: "לממן" },
    {  en: "Furnish",  he: "לרהט / לספק" },
    {  en: "Further",  he: "לקדם" },
    {  en: "Gain",  he: "להשיג / לצבור" },
    {  en: "Gambel",  he: "להמר" },
    {  en: "Gather",  he: "לאסוף" },
    {  en: "Gaze",  he: "לבהות" },
    {  en: "Generate",  he: "לייצר" },
    {  en: "Get",  he: "לקבל / להשיג" },
    {  en: "Give",  he: "לתת" },
    {  en: "Glance",  he: "להעיף מבט" },
    {  en: "Glare",  he: "לבהור בזעם" },
    {  en: "Glide",  he: "לגלוש / לדאות" },
    {  en: "Glimpse",  he: "להבחין לרגע" },
    {  en: "Go",  he: "ללכת" },
    {  en: "Govern",  he: "למשול" },
    {  en: "Grab",  he: "לתפוס" },
    {  en: "Grade",  he: "לדרג" },
    {  en: "Grant",  he: "להעניק" },
    {  en: "Grasp",  he: "לתפוס / להבין" },
    {  en: "Greet",  he: "לברך לשלום" },
    {  en: "Grin",  he: "לחייך חיוך רחב" },
    {  en: "Grind",  he: "לטחון" },
    {  en: "Grip",  he: "לאחוז חזק" },
    {  en: "Grow",  he: "לגדול" },
    {  en: "Guarantee",  he: "להבטיח" },
    {  en: "Guard",  he: "לשמור / לאבטח" },
    {  en: "Guess",  he: "לנחש" },
    {  en: "Guide",  he: "להדריך" },
    {  en: "Handle",  he: "לטפל" },
    {  en: "Hang",  he: "לתלות" },
    {  en: "Happen",  he: "לקרות" },
    {  en: "Harm",  he: "להזיק" },
    {  en: "Harvest",  he: "לקצור" },
    {  en: "Hate",  he: "לשנוא" },
    {  en: "Experience",  he: "לחוות" },
    {  en: "Experiment",  he: "לערוך ניסוי" },
    {  en: "Explain",  he: "להסביר" },
    {  en: "Explode",  he: "להתפוצץ" },
    {  en: "Explore",  he: "לחקור" },
    {  en: "Export",  he: "לייצא" },
    {  en: "Expose",  he: "לחשוף" },
    {  en: "Express",  he: "לבטא" },
    {  en: "Extend",  he: "להאריך / להרחיב" },
    {  en: "Extract",  he: "לחלץ" },
    {  en: "Face",  he: "להתמודד" },
    {  en: "Facilitate",  he: "להקל" },
    {  en: "Fade",  he: "לדהות" },
    {  en: "Fail",  he: "לכישלון" },
    {  en: "Fall",  he: "ליפול" },
    {  en: "Familiarize",  he: "להכיר / להתרגל" },
    {  en: "Fancy",  he: "לדמיין / לחשוק" },
    {  en: "Farm",  he: "לעבד אדמה" },
    {  en: "Fascinate",  he: "לרתק" },
    {  en: "Fashion",  he: "לעצב" },
    {  en: "Fasten",  he: "לחבר / לקשור" },
    {  en: "Favor",  he: "להעדיף / לחבב" },
    {  en: "Fear",  he: "לפחד" },
    {  en: "Feature",  he: "להציג / לאפיין" },
    {  en: "Feed",  he: "להאכיל" },
    {  en: "Feel",  he: "להרגיש" },
    {  en: "Ferry",  he: "לשנע (במעבורת)" },
    {  en: "Fetch",  he: "להביא" },
    {  en: "Fight",  he: "להילחם" },
    {  en: "Figure",  he: "לחשב / להבין" },
    {  en: "File",  he: "לתייק / להגיש" },
    {  en: "Fill",  he: "למלא" },
    {  en: "Filter",  he: "לסנן" },
    {  en: "Finance",  he: "לממן" },
    {  en: "Find",  he: "למצוא" },
    {  en: "Fine",  he: "לקנוס" },
    {  en: "Finish",  he: "לסיים" },
    {  en: "Fire",  he: "לירות / לפטר" },
    {  en: "Fit",  he: "להתאים" },
    {  en: "Fix",  he: "לתקן" },
    {  en: "Flash",  he: "להבהב" },
    {  en: "Flatten",  he: "לשטח" },
    {  en: "Flee",  he: "לברוח" },
    {  en: "Float",  he: "לצוף" },
    {  en: "Flood",  he: "להציף" },
    {  en: "Flow",  he: "לזרום" },
    {  en: "Flourish",  he: "לשגשג" },
    {  en: "Fold",  he: "לקפל" },
    {  en: "Follow",  he: "לעקוב" },
    {  en: "Force",  he: "לאלץ" },
    {  en: "Enable",  he: "לאפשר" },
    {  en: "Encounter",  he: "להיתקל ב-" },
    {  en: "Encourage",  he: "לעודד" },
    {  en: "End",  he: "לסיים" },
    {  en: "Endure",  he: "לשאת / לסבול" },
    {  en: "Enforce",  he: "לאכוף" },
    {  en: "Engage",  he: "לעסוק / לערב" },
    {  en: "Engineer",  he: "לתכנן / להנדס" },
    {  en: "Enhance",  he: "לשפר" },
    {  en: "Enjoy",  he: "ליהנות" },
    {  en: "Enlarge",  he: "להגדיל" },
    {  en: "Enlighten",  he: "להאיר (מבחינה רוחנית/אינטלקטואלית)" },
    {  en: "Enlist",  he: "להתגייס / לגייס" },
    {  en: "Enrich",  he: "להעשיר" },
    {  en: "Enroll",  he: "להירשם" },
    {  en: "Ensure",  he: "להבטיח" },
    {  en: "Enter",  he: "להיכנס" },
    {  en: "Entertain",  he: "לבדר" },
    {  en: "Entitle",  he: "להקנות זכות" },
    {  en: "Envision",  he: "לדמיין / לחזות" },
    {  en: "Equal",  he: "להשתוות ל-" },
    {  en: "Equip",  he: "לצייד" },
    {  en: "Erase",  he: "למחוק" },
    {  en: "Erect",  he: "להקים / לבנות" },
    {  en: "Erode",  he: "לשחוק" },
    {  en: "Escape",  he: "לברוח" },
    {  en: "Establish",  he: "להקים / לבסס" },
    {  en: "Estimate",  he: "להעריך" },
    {  en: "Evacuate",  he: "לפנות" },
    {  en: "Evaluate",  he: "להעריך" },
    {  en: "Evaporate",  he: "להתאדות" },
    {  en: "Evolve",  he: "להתפתח" },
    {  en: "Exaggerate",  he: "להגזים" },
    {  en: "Examine",  he: "לבחון" },
    {  en: "Exceed",  he: "לחרוג / לעלות על" },
    {  en: "Excel",  he: "להצטיין" },
    {  en: "Except",  he: "להוציא מן הכלל" },
    {  en: "Exchange",  he: "להחליף" },
    {  en: "Excite",  he: "לרגש" },
    {  en: "Exclude",  he: "להוציא / למנוע" },
    {  en: "Excuse",  he: "לסלוח / להתנצל" },
    {  en: "Execute",  he: "לבצע" },
    {  en: "Exercise",  he: "להתאמן / להפעיל" },
    {  en: "Exert",  he: "להפעיל (כוח)" },
    {  en: "Exhibit",  he: "להציג" },
    {  en: "Exist",  he: "להתקיים" },
    {  en: "Exit",  he: "לצאת" },
    {  en: "Expand",  he: "להתרחב" },
    {  en: "Expect",  he: "לצפות" },
    {  en: "Expel",  he: "לגרש" },
    {  en: "Display",  he: "להציג" },
    {  en: "Dispose",  he: "להיפטר מ-" },
    {  en: "Disprove",  he: "להפריך" },
    {  en: "Disrupt",  he: "לשבש" },
    {  en: "Dissolve",  he: "להמיס / להתמוסס" },
    {  en: "Distinguish",  he: "להבחין" },
    {  en: "Distort",  he: "לעוות" },
    {  en: "Distract",  he: "להסיח את הדעת" },
    {  en: "Distress",  he: "לגרום למצוקה" },
    {  en: "Distribute",  he: "להפיץ" },
    {  en: "Disturb",  he: "להפריע" },
    {  en: "Dive",  he: "לצלול" },
    {  en: "Diverge",  he: "להתפצל / לסטות" },
    {  en: "Diversify",  he: "לגוון" },
    {  en: "Divide",  he: "לחלק" },
    {  en: "Divorce",  he: "להתגרש" },
    {  en: "Dominate",  he: "לשלוט" },
    {  en: "Donate",  he: "לתרום" },
    {  en: "Double",  he: "להכפיל" },
    {  en: "Doubt",  he: "להטיל ספק" },
    {  en: "Drag",  he: "לגרור" },
    {  en: "Drain",  he: "לנקז" },
    {  en: "Draw",  he: "לצייר / למשוך" },
    {  en: "Dread",  he: "לפחד מאוד" },
    {  en: "Dream",  he: "לחלום" },
    {  en: "Dress",  he: "להתלבש / להלביש" },
    {  en: "Drift",  he: "לצוף / להיסחף" },
    {  en: "Drill",  he: "לקדוח / לאמן" },
    {  en: "Drink",  he: "לשתות" },
    {  en: "Drive",  he: "לנהוג" },
    {  en: "Drop",  he: "להפיל / לרדת" },
    {  en: "Drown",  he: "לטבוע / להטביע" },
    {  en: "Dry",  he: "לייבש" },
    {  en: "Dump",  he: "לזרוק / להשליך" },
    {  en: "Duplicate",  he: "לשכפל" },
    {  en: "Earn",  he: "להרוויח" },
    {  en: "Ease",  he: "להקל" },
    {  en: "Eat",  he: "לאכול" },
    {  en: "Echo",  he: "להדהד" },
    {  en: "Edit",  he: "לערוך" },
    {  en: "Educate",  he: "לחנך" },
    {  en: "Effect",  he: "להשפיע / לגרום" },
    {  en: "Elect",  he: "לבחור (בבחירות)" },
    {  en: "Elevate",  he: "להרים / לרומם" },
    {  en: "Eliminate",  he: "לחסל" },
    {  en: "Embrace",  he: "לחבק / לאמץ" },
    {  en: "Emerge",  he: "לצוף / להופיע" },
    {  en: "Emphasize",  he: "להדגיש" },
    {  en: "Employ",  he: "להעסיק / להשתמש" },
    {  en: "Delight",  he: "לשמח" },
    {  en: "Deliver",  he: "למסור" },
    {  en: "Demand",  he: "לדרוש" },
    {  en: "Demonstrate",  he: "להדגים" },
    {  en: "Deny",  he: "להכחיש" },
    {  en: "Depart",  he: "לצאת / לעזוב" },
    {  en: "Depend",  he: "להיות תלוי ב-" },
    {  en: "Depict",  he: "לתאר" },
    {  en: "Deploy",  he: "לפרוס / להציב" },
    {  en: "Deposit",  he: "להפקיד" },
    {  en: "Depress",  he: "לדכא / ללחוץ" },
    {  en: "Deprive",  he: "לשלול" },
    {  en: "Derive",  he: "לגזור / לנבוע" },
    {  en: "Descend",  he: "לרדת" },
    {  en: "Describe",  he: "לתאר" },
    {  en: "Deserve",  he: "להיות ראוי ל-" },
    {  en: "Design",  he: "לעצב" },
    {  en: "Designate",  he: "לייעד / למנות" },
    {  en: "Desire",  he: "לרצות / לחפוץ" },
    {  en: "Destroy",  he: "להרוס" },
    {  en: "Detach",  he: "להפריד / לנתק" },
    {  en: "Detect",  he: "לגלות" },
    {  en: "Deter",  he: "להרתיע" },
    {  en: "Determine",  he: "לקבוע" },
    {  en: "Develop",  he: "לפתח" },
    {  en: "Deviate",  he: "לסטות" },
    {  en: "Devise",  he: "לתכנן / להמציא" },
    {  en: "Devote",  he: "להקדיש" },
    {  en: "Diagnose",  he: "לאבחן" },
    {  en: "Dictate",  he: "להכתיב" },
    {  en: "Differ",  he: "להיות שונה" },
    {  en: "Differentiate",  he: "להבדיל" },
    {  en: "Dig",  he: "לחפור" },
    {  en: "Dilute",  he: "לדלל" },
    {  en: "Diminish",  he: "להפחית / להתמעט" },
    {  en: "Direct",  he: "לכוון / לנהל" },
    {  en: "Disagree",  he: "לא להסכים" },
    {  en: "Disappear",  he: "להיעלם" },
    {  en: "Disappoint",  he: "לאכזב" },
    {  en: "Discard",  he: "להשליך" },
    {  en: "Discharge",  he: "לשחרר / לפרוק" },
    {  en: "Disclose",  he: "לחשוף" },
    {  en: "Disconnect",  he: "לנתק" },
    {  en: "Discourage",  he: "לייאש / להרתיע" },
    {  en: "Discover",  he: "לגלות" },
    {  en: "Discuss",  he: "לדון" },
    {  en: "Dislike",  he: "לא לאהוב" },
    {  en: "Dismiss",  he: "לפטר / לדחות" },
    {  en: "Displace",  he: "להזיז / לעקור" },
    {  en: "Correct",  he: "לתקן" },
    {  en: "Correspond",  he: "להתכתב / להתאים" },
    {  en: "Corrupt",  he: "להשחית" },
    {  en: "Cost",  he: "לעלות (במחיר)" },
    {  en: "Cough",  he: "להשתעל" },
    {  en: "Counsel",  he: "לייעץ" },
    {  en: "Count",  he: "לספור" },
    {  en: "Counter",  he: "להתנגד / לפעול נגד" },
    {  en: "Couple",  he: "לחבר" },
    {  en: "Cover",  he: "לכסות" },
    {  en: "Crack",  he: "לסדוק / לפצח" },
    {  en: "Craft",  he: "ליצור במלאכת יד" },
    {  en: "Crash",  he: "להתרסק" },
    {  en: "Crave",  he: "להשתוקק" },
    {  en: "Crawl",  he: "לזחול" },
    {  en: "Create",  he: "ליצור" },
    {  en: "Credit",  he: "לזכות (בחשבון)" },
    {  en: "Creep",  he: "לזחול / להתגנב" },
    {  en: "Criticize",  he: "לבקר" },
    {  en: "Cross",  he: "לחצות" },
    {  en: "Crush",  he: "למעוך" },
    {  en: "Cry",  he: "לבכות / לצעוק" },
    {  en: "Cultivate",  he: "לשמר / לעבד (אדמה)" },
    {  en: "Cure",  he: "לרפא" },
    {  en: "Curl",  he: "להתכרבל / לסלסל" },
    {  en: "Curve",  he: "לעקם" },
    {  en: "Custom",  he: "להתאים אישית" },
    {  en: "Cut",  he: "לחתוך" },
    {  en: "Damage",  he: "להזיק" },
    {  en: "Dance",  he: "לרקוד" },
    {  en: "Dare",  he: "להעז" },
    {  en: "Date",  he: "לתארך / לצאת לדייט" },
    {  en: "Deal",  he: "לעסוק / להתמודד" },
    {  en: "Debate",  he: "להתווכח / לדון" },
    {  en: "Decide",  he: "להחליט" },
    {  en: "Declare",  he: "להכריז" },
    {  en: "Decline",  he: "לסרב / לרדת" },
    {  en: "Decorate",  he: "לקשט" },
    {  en: "Decrease",  he: "להפחית" },
    {  en: "Dedicate",  he: "להקדיש" },
    {  en: "Deduct",  he: "לנכות" },
    {  en: "Deem",  he: "לראות כ- / לסבור" },
    {  en: "Defeat",  he: "להביס" },
    {  en: "Defend",  he: "להגן" },
    {  en: "Define",  he: "להגדיר" },
    {  en: "Deflate",  he: "לנפח" },
    {  en: "Deform",  he: "לעוות" },
    {  en: "Delay",  he: "לעכב" },
    {  en: "Delegate",  he: "להאציל סמכויות" },
    {  en: "Compress",  he: "לדחוס" },
    {  en: "Compromise",  he: "להתפשר" },
    {  en: "Conceal",  he: "להסתיר" },
    {  en: "Concede",  he: "להודות ב- / לוותר" },
    {  en: "Conceive",  he: "להרות / להעלות על הדעת" },
    {  en: "Concentrate",  he: "להתרכז" },
    {  en: "Concern",  he: "לדאוג / לעניין" },
    {  en: "Conclude",  he: "להסיק / לסיים" },
    {  en: "Condemn",  he: "לגנות" },
    {  en: "Conduct",  he: "לערוך / לנהל" },
    {  en: "Confer",  he: "להיוועץ / להעניק" },
    {  en: "Confess",  he: "להתוודות" },
    {  en: "Confine",  he: "להגביל / לכלוא" },
    {  en: "Confirm",  he: "לאשר" },
    {  en: "Conflict",  he: "להתנגש" },
    {  en: "Confront",  he: "להתעמת" },
    {  en: "Confuse",  he: "לבלבל" },
    {  en: "Congratulate",  he: "לברך (על הצלחה)" },
    {  en: "Connect",  he: "לחבר" },
    {  en: "Conquer",  he: "לכבוש" },
    {  en: "Consent",  he: "להסכים" },
    {  en: "Conserve",  he: "לשמר" },
    {  en: "Consider",  he: "לשקול" },
    {  en: "Consist",  he: "להיות מורכב מ-" },
    {  en: "Consolidate",  he: "לאחד / לגבש" },
    {  en: "Constitute",  he: "להוות" },
    {  en: "Construct",  he: "לבנות" },
    {  en: "Consult",  he: "להתייעץ" },
    {  en: "Consume",  he: "לצרוך" },
    {  en: "Contain",  he: "להכיל" },
    {  en: "Contemplate",  he: "להרהר / לשקול" },
    {  en: "Contend",  he: "לטעון / להתחרות" },
    {  en: "Content",  he: "להסתפק" },
    {  en: "Contest",  he: "לערער / להתחרות" },
    {  en: "Continue",  he: "להמשיך" },
    {  en: "Contract",  he: "לכווץ / להתקשר בחוזה" },
    {  en: "Contradict",  he: "לסתור" },
    {  en: "Contribute",  he: "לתרום" },
    {  en: "Control",  he: "לשלוט" },
    {  en: "Convene",  he: "לכנס (אסיפה)" },
    {  en: "Converge",  he: "להתכנס" },
    {  en: "Converse",  he: "לשוחח" },
    {  en: "Convert",  he: "להמיר" },
    {  en: "Convey",  he: "להעביר (מסר)" },
    {  en: "Convict",  he: "להרשיע" },
    {  en: "Convince",  he: "לשכנע" },
    {  en: "Cooperate",  he: "לשתף פעולה" },
    {  en: "Coordinate",  he: "לתאם" },
    {  en: "Cope",  he: "להתמודד" },
    {  en: "Copy",  he: "להעתיק" },
    {  en: "Challenge",  he: "לאתגר" },
    {  en: "Change",  he: "לשנות" },
    {  en: "Characterize",  he: "לאפיין" },
    {  en: "Charge",  he: "לחייב / להטעין" },
    {  en: "Chase",  he: "לרדוף" },
    {  en: "Chat",  he: "לשוחח" },
    {  en: "Check",  he: "לבדוק" },
    {  en: "Cheer",  he: "לעודד" },
    {  en: "Chew",  he: "ללעוס" },
    {  en: "Choose",  he: "לבחור" },
    {  en: "Chop",  he: "לקצוץ" },
    {  en: "Circle",  he: "להקיף / לחוג" },
    {  en: "Circulate",  he: "להפיץ / לנוע" },
    {  en: "Cite",  he: "לצטט / לציין" },
    {  en: "Claim",  he: "לטעון / לתבוע" },
    {  en: "Clarify",  he: "להבהיר" },
    {  en: "Clash",  he: "להתנגש" },
    {  en: "Classify",  he: "לסווג" },
    {  en: "Clean",  he: "לנקות" },
    {  en: "Clear",  he: "לנקות / לפנות" },
    {  en: "Click",  he: "ללחוץ" },
    {  en: "Climb",  he: "לטפס" },
    {  en: "Cling",  he: "להיצמד" },
    {  en: "Close",  he: "לסגור" },
    {  en: "Clothe",  he: "להלביש" },
    {  en: "Coexist",  he: "להתקיים יחד" },
    {  en: "Coincide",  he: "לחפוף / להתלכד" },
    {  en: "Collaborate",  he: "לשתף פעולה" },
    {  en: "Collapse",  he: "לקרוס" },
    {  en: "Collect",  he: "לאסוף" },
    {  en: "Combat",  he: "להילחם" },
    {  en: "Combine",  he: "לשלב" },
    {  en: "Come",  he: "לבוא" },
    {  en: "Comfort",  he: "לנחם" },
    {  en: "Command",  he: "לפקד" },
    {  en: "Commence",  he: "להתחיל" },
    {  en: "Comment",  he: "להגיב" },
    {  en: "Commit",  he: "להתחייב" },
    {  en: "Communicate",  he: "לתקשר" },
    {  en: "Compare",  he: "להשוות" },
    {  en: "Compel",  he: "להכריח" },
    {  en: "Compensate",  he: "לפצות" },
    {  en: "Compete",  he: "להתחרות" },
    {  en: "Complain",  he: "להתלונן" },
    {  en: "Complete",  he: "להשלים" },
    {  en: "Complicate",  he: "לסבך" },
    {  en: "Comply",  he: "לציית" },
    {  en: "Compose",  he: "להלחין / להרכיב" },
    {  en: "Comprehend",  he: "להבין" },
    {  en: "Bless",  he: "לברך" },
    {  en: "Blind",  he: "לעוור" },
    {  en: "Block",  he: "לחסום" },
    {  en: "Bloom",  he: "לפרוח" },
    {  en: "Blush",  he: "להסמיק" },
    {  en: "Boast",  he: "להתרברב" },
    {  en: "Boil",  he: "להרתיח / לרתוח" },
    {  en: "Bomb",  he: "להפציץ" },
    {  en: "Bond",  he: "לקשור / ליצור קשר" },
    {  en: "Book",  he: "להזמין / לרשום" },
    {  en: "Boost",  he: "להגביר / לעודד" },
    {  en: "Bore",  he: "לשעמם" },
    {  en: "Borrow",  he: "ללוות" },
    {  en: "Bother",  he: "להטריד" },
    {  en: "Bounce",  he: "לקפוץ / להקפיץ" },
    {  en: "Bow",  he: "לקוד קידה" },
    {  en: "Branch",  he: "להתפצל" },
    {  en: "Brand",  he: "למתג" },
    {  en: "Break",  he: "לשבור" },
    {  en: "Breathe",  he: "לנשום" },
    {  en: "Breed",  he: "להתרבות / לגדל" },
    {  en: "Brief",  he: "לתדרך" },
    {  en: "Brighten",  he: "להאיר / לשפר" },
    {  en: "Bring",  he: "להביא" },
    {  en: "Broadcast",  he: "לשדר" },
    {  en: "Broaden",  he: "להרחיב" },
    {  en: "Brush",  he: "לצחצח / להבריש" },
    {  en: "Bubble",  he: "לבעבע" },
    {  en: "Budget",  he: "לתקצב" },
    {  en: "Build",  he: "לבנות" },
    {  en: "Burn",  he: "לשרוף" },
    {  en: "Burst",  he: "להתפוצץ" },
    {  en: "Bury",  he: "לקבור" },
    {  en: "Buy",  he: "לקנות" },
    {  en: "Buzz",  he: "לזמזם" },
    {  en: "Calculate",  he: "לחשב" },
    {  en: "Call",  he: "לקרוא / להתקשר" },
    {  en: "Calm",  he: "להרגיע" },
    {  en: "Camp",  he: "לחנות (באוהל)" },
    {  en: "Cancel",  he: "לבטל" },
    {  en: "Capture",  he: "ללכוד" },
    {  en: "Care",  he: "לדאוג / לאכפת" },
    {  en: "Carry",  he: "לשאת" },
    {  en: "Carve",  he: "לגלף / לחתוך" },
    {  en: "Cast",  he: "להטיל / ללהק" },
    {  en: "Catch",  he: "לתפוס" },
    {  en: "Cause",  he: "לגרום" },
    {  en: "Cease",  he: "להפסיק" },
    {  en: "Celebrate",  he: "לחגוג" },
    {  en: "Center",  he: "למרכז" },
    {  en: "Assert",  he: "לטעון / לאשש" },
    {  en: "Assess",  he: "להעריך" },
    {  en: "Assign",  he: "להקצות / לשייך" },
    {  en: "Assist",  he: "לסייע" },
    {  en: "Associate",  he: "לקשר / להתחבר" },
    {  en: "Assume",  he: "להניח" },
    {  en: "Assure",  he: "להבטיח" },
    {  en: "Attach",  he: "לצרף / לחבר" },
    {  en: "Attain",  he: "להשיג" },
    {  en: "Attempt",  he: "לנסות" },
    {  en: "Attend",  he: "להשתתף / לטפל" },
    {  en: "Attract",  he: "למשוך" },
    {  en: "Attribute",  he: "לייחס ל-" },
    {  en: "Audit",  he: "לבקר" },
    {  en: "Augment",  he: "להגדיל / להרחיב" },
    {  en: "Authorize",  he: "לאשר" },
    {  en: "Automate",  he: "לאוטומט" },
    {  en: "Avail",  he: "להועיל" },
    {  en: "Average",  he: "לממוצע" },
    {  en: "Avoid",  he: "להימנע" },
    {  en: "Awaken",  he: "להתעורר / לעורר" },
    {  en: "Award",  he: "להעניק פרס" },
    {  en: "Back",  he: "לתמוך / לגבות" },
    {  en: "Bake",  he: "לאפות" },
    {  en: "Balance",  he: "לאזן" },
    {  en: "Ban",  he: "לאסור" },
    {  en: "Band",  he: "לחבוש / לקשור" },
    {  en: "Bank",  he: "להפקיד בבנק" },
    {  en: "Bargain",  he: "להתמקח" },
    {  en: "Base",  he: "לבסס" },
    {  en: "Bathe",  he: "להתרחץ" },
    {  en: "Battle",  he: "להילחם" },
    {  en: "Bear",  he: "לשאת / לסבול / ללדת" },
    {  en: "Beat",  he: "להכות / להביס" },
    {  en: "Become",  he: "להפוך ל-" },
    {  en: "Beg",  he: "להתחנן" },
    {  en: "Begin",  he: "להתחיל" },
    {  en: "Behave",  he: "להתנהג" },
    {  en: "Believe",  he: "להאמין" },
    {  en: "Belong",  he: "להיות שייך ל-" },
    {  en: "Bend",  he: "לכופף" },
    {  en: "Benefit",  he: "להועיל" },
    {  en: "Bet",  he: "להתערב" },
    {  en: "Bid",  he: "להציע מחיר / להציע" },
    {  en: "Bind",  he: "לקשור" },
    {  en: "Bite",  he: "לנשוך" },
    {  en: "Blame",  he: "להאשים" },
    {  en: "Blast",  he: "לפוצץ / לגרום לפיצוץ" },
    {  en: "Bleed",  he: "לדמם" },
    {  en: "Admire",  he: "להעריץ" },
    {  en: "Admit",  he: "להודות" },
    {  en: "Adopt",  he: "לאמץ" },
    {  en: "Advance",  he: "לקדם / להתקדם" },
    {  en: "Advertise",  he: "לפרסם" },
    {  en: "Advise",  he: "לייעץ" },
    {  en: "Advocate",  he: "לתמוך ב- / לסנגר" },
    {  en: "Affect",  he: "להשפיע" },
    {  en: "Affirm",  he: "לאשר / לאשש" },
    {  en: "Afford",  he: "להרשות לעצמו" },
    {  en: "Aggravate",  he: "להחמיר" },
    {  en: "Agree",  he: "להסכים" },
    {  en: "Aid",  he: "לסייע" },
    {  en: "Aim",  he: "לכוון" },
    {  en: "Alert",  he: "להתריע" },
    {  en: "Align",  he: "ליישר / להתיישר" },
    {  en: "Allege",  he: "לטעון" },
    {  en: "Allocate",  he: "להקצות" },
    {  en: "Allow",  he: "לאפשר" },
    {  en: "Alter",  he: "לשנות" },
    {  en: "Amass",  he: "לצבור" },
    {  en: "Amend",  he: "לתקן / לשנות" },
    {  en: "Amount",  he: "להסתכם ב-" },
    {  en: "Amuse",  he: "לשעשע" },
    {  en: "Analyze",  he: "לנתח" },
    {  en: "Anchor",  he: "לעגן" },
    {  en: "Animate",  he: "להנפיש / להחיות" },
    {  en: "Announce",  he: "להודיע" },
    {  en: "Annoy",  he: "להרגיז" },
    {  en: "Anticipate",  he: "לצפות" },
    {  en: "Apologize",  he: "להתנצל" },
    {  en: "Appeal",  he: "לפנות / לערער" },
    {  en: "Appear",  he: "להופיע / להיראות" },
    {  en: "Applaud",  he: "למחוא כפיים" },
    {  en: "Apply",  he: "ליישם / לפנות בבקשה" },
    {  en: "Appoint",  he: "למנות" },
    {  en: "Appreciate",  he: "להעריך" },
    {  en: "Approach",  he: "לגשת" },
    {  en: "Approve",  he: "לאשר" },
    {  en: "Arbitrate",  he: "לבורר" },
    {  en: "Argue",  he: "להתווכח" },
    {  en: "Arise",  he: "לעלות / לצוץ" },
    {  en: "Arm",  he: "לחמש" },
    {  en: "Arrange",  he: "לארגן" },
    {  en: "Arrest",  he: "לעצור" },
    {  en: "Arrive",  he: "להגיע" },
    {  en: "Articulate",  he: "לבטא" },
    {  en: "Ascend",  he: "לעלות" },
    {  en: "Ask",  he: "לשאול" },
    {  en: "Want",  he: "לרצות" },
    {  en: "Ward",  he: "לשמור / להתגונן" },
    {  en: "Warm",  he: "לחמם" },
    {  en: "Warn",  he: "להזהיר" },
    {  en: "Wash",  he: "לשטוף" },
    {  en: "Waste",  he: "לבזבז" },
    {  en: "Watch",  he: "לצפות" },
    {  en: "Wave",  he: "לנופף" },
    {  en: "Weaken",  he: "להחליש" },
    {  en: "Wear",  he: "ללבוש / לשחוק" },
    {  en: "Weigh",  he: "לשקול" },
    {  en: "Welcome",  he: "לקבל בברכה" },
    {  en: "Wet",  he: "להרטיב" },
    {  en: "Whine",  he: "ליילל / להתלונן בבכיינות" },
    {  en: "Whisper",  he: "ללחוש" },
    {  en: "Whistle",  he: "לשרוק" },
    {  en: "Win",  he: "לנצח" },
    {  en: "Wind",  he: "ללפף / לנשוב (רוח)" },
    {  en: "Wipe",  he: "לנגב" },
    {  en: "Wish",  he: "לאחל" },
    {  en: "Withdraw",  he: "למשוך / לסגת" },
    {  en: "Withhold",  he: "לעכב / למנוע" },
    {  en: "Witness",  he: "להיות עד ל-" },
    {  en: "Wonder",  he: "לתהות" },
    {  en: "Work",  he: "לעבוד" },
    {  en: "Worry",  he: "לדאוג" },
    {  en: "Worship",  he: "לסגוד" },
    {  en: "Wrap",  he: "לעטוף" },
    {  en: "Write",  he: "לכתוב" },
    {  en: "Yield",  he: "להניב / לוותר" },
    {  en: "Zip",  he: "לרכוס" },
    {  en: "Zoom",  he: "להתקרב / להתרחק במהירות" },
    {  en: "Abide",  he: "לציית / לשכון" },
    {  en: "Abolish",  he: "לבטל" },
    {  en: "Accelerate",  he: "להאיץ" },
    {  en: "Accommodate",  he: "לארח / להתאים" },
    {  en: "Accompany",  he: "ללוות" },
    {  en: "Accomplish",  he: "להשלים / להשיג" },
    {  en: "Account",  he: "להסביר / לדווח" },
    {  en: "Accumulate",  he: "לצבור" },
    {  en: "Accuse",  he: "להאשים" },
    {  en: "Achieve",  he: "להשיג" },
    {  en: "Acknowledge",  he: "להכיר ב- / להודות ב-" },
    {  en: "Acquire",  he: "לרכוש" },
    {  en: "Act",  he: "לפעול" },
    {  en: "Adapt",  he: "להסתגל" },
    {  en: "Addict",  he: "להתמכר" },
    {  en: "Address",  he: "לפנות ל- / לטפל ב-" },
    {  en: "Adjust",  he: "להתאים / לכוונן" },
    {  en: "Administer",  he: "לנהל / לספק" },
    {  en: "Top",  he: "לעלות על / לכסות" },
    {  en: "Total",  he: "לסכם" },
    {  en: "Touch",  he: "לגעת" },
    {  en: "Trace",  he: "לעקוב / להתחקות" },
    {  en: "Track",  he: "לעקוב" },
    {  en: "Trade",  he: "לסחור" },
    {  en: "Train",  he: "לאמן" },
    {  en: "Transfer",  he: "להעביר" },
    {  en: "Transform",  he: "לשנות / להפוך" },
    {  en: "Translate",  he: "לתרגם" },
    {  en: "Transmit",  he: "לשדר / להעביר" },
    {  en: "Transport",  he: "להוביל / לשנע" },
    {  en: "Trap",  he: "ללכוד" },
    {  en: "Travel",  he: "לטייל / לנסוע" },
    {  en: "Treat",  he: "לטפל / להתייחס" },
    {  en: "Tremble",  he: "לרעוד" },
    {  en: "Trend",  he: "לנטות / להיות במגמה" },
    {  en: "Trigger",  he: "להפעיל / לגרום" },
    {  en: "Trip",  he: "למעוד / לטייל" },
    {  en: "Trust",  he: "לבטוח" },
    {  en: "Try",  he: "לנסות" },
    {  en: "Turn",  he: "לפנות / להסתובב" },
    {  en: "Twist",  he: "לסובב / לעקם" },
    {  en: "Type",  he: "להקליד" },
    {  en: "Undergo",  he: "לעבור / לחוות" },
    {  en: "Understand",  he: "להבין" },
    {  en: "Undertake",  he: "לקחת על עצמו" },
    {  en: "Unite",  he: "לאחד" },
    {  en: "Unload",  he: "לפרוק" },
    {  en: "Unlock",  he: "לפתוח (מנעול)" },
    {  en: "Unpack",  he: "לפרוק (מזוודה)" },
    {  en: "Update",  he: "לעדכן" },
    {  en: "Upgrade",  he: "לשדרג" },
    {  en: "Upset",  he: "להרגיז / להדאיג" },
    {  en: "Urge",  he: "להפציר / לדחוק" },
    {  en: "Use",  he: "להשתמש" },
    {  en: "Utilize",  he: "לנצל" },
    {  en: "Vanish",  he: "להיעלם" },
    {  en: "Vary",  he: "להשתנות" },
    {  en: "Venture",  he: "להעז / להסתכן" },
    {  en: "Verify",  he: "לאמת" },
    {  en: "View",  he: "לצפות / לראות" },
    {  en: "Violate",  he: "להפר" },
    {  en: "Visit",  he: "לבקר" },
    {  en: "Visualize",  he: "לדמיין" },
    {  en: "Voice",  he: "לבטא" },
    {  en: "Vote",  he: "להצביע" },
    {  en: "Wait",  he: "לחכות" },
    {  en: "Wake",  he: "להתעורר" },
    {  en: "Walk",  he: "ללכת" },
    {  en: "Stretch",  he: "למתוח" },
    {  en: "Strike",  he: "להכות / לשבות" },
    {  en: "Strive",  he: "לשאוף / להתאמץ" },
    {  en: "Structure",  he: "לבנות / לארגן" },
    {  en: "Struggle",  he: "להיאבק" },
    {  en: "Study",  he: "ללמוד" },
    {  en: "Submit",  he: "להגיש / להיכנע" },
    {  en: "Succeed",  he: "להצליח" },
    {  en: "Suffer",  he: "לסבול" },
    {  en: "Suggest",  he: "להציע" },
    {  en: "Suit",  he: "להתאים" },
    {  en: "Summarize",  he: "לסכם" },
    {  en: "Supervise",  he: "לפקח" },
    {  en: "Supplement",  he: "להשלים" },
    {  en: "Supply",  he: "לספק" },
    {  en: "Support",  he: "לתמוך" },
    {  en: "Suppose",  he: "להניח" },
    {  en: "Suppress",  he: "לדכא" },
    {  en: "Surprise",  he: "להפתיע" },
    {  en: "Surround",  he: "להקיף" },
    {  en: "Survive",  he: "לשרוד" },
    {  en: "Suspect",  he: "לחשוד" },
    {  en: "Sustain",  he: "לקיים / לשמר" },
    {  en: "Swear",  he: "להישבע / לקלל" },
    {  en: "Sweep",  he: "לטאטא" },
    {  en: "Swim",  he: "לשחות" },
    {  en: "Swing",  he: "להתנדנד" },
    {  en: "Switch",  he: "להחליף" },
    {  en: "Symbolize",  he: "לסמל" },
    {  en: "Synthesize",  he: "לסנתז" },
    {  en: "Systematize",  he: "לסדר / למיין" },
    {  en: "Table",  he: "להגיש הצעה (בדיון)" },
    {  en: "Tackle",  he: "לטפל ב-" },
    {  en: "Take",  he: "לקחת" },
    {  en: "Talk",  he: "לדבר" },
    {  en: "Target",  he: "למקד" },
    {  en: "Taste",  he: "לטעום" },
    {  en: "Teach",  he: "ללמד" },
    {  en: "Tear",  he: "לקרוע" },
    {  en: "Tell",  he: "לספר" },
    {  en: "Tend",  he: "לנטות ל-" },
    {  en: "Terminate",  he: "לסיים" },
    {  en: "Test",  he: "לבחון / לבדוק" },
    {  en: "Thank",  he: "להודות" },
    {  en: "Think",  he: "לחשוב" },
    {  en: "Threaten",  he: "לאיים" },
    {  en: "Throw",  he: "לזרוק" },
    {  en: "Thrust",  he: "לדחוף / לדקור" },
    {  en: "Tighten",  he: "להדק" },
    {  en: "Tolerate",  he: "לסבול / לספוג" },
    {  en: "Serve",  he: "לשרת / להגיש" },
    {  en: "Set",  he: "לקבוע / להגדיר" },
    {  en: "Settle",  he: "להתיישב / ליישב" },
    {  en: "Shake",  he: "לנער" },
    {  en: "Shape",  he: "לעצב" },
    {  en: "Share",  he: "לשתף" },
    {  en: "Shed",  he: "להשיל / לפזר" },
    {  en: "Shift",  he: "להזיז / להעביר" },
    {  en: "Shine",  he: "לזהור" },
    {  en: "Shoot",  he: "לירות" },
    {  en: "Shop",  he: "לקנות" },
    {  en: "Show",  he: "להראות" },
    {  en: "Shrink",  he: "להתכווץ" },
    {  en: "Shut",  he: "לסגור" },
    {  en: "Sight",  he: "לראות / להבחין" },
    {  en: "Sign",  he: "לחתום / לאותת" },
    {  en: "Signal",  he: "לאותת" },
    {  en: "Signify",  he: "לציין / לסמל" },
    {  en: "Simulate",  he: "לדמות" },
    {  en: "Sing",  he: "לשיר" },
    {  en: "Sink",  he: "לשקוע" },
    {  en: "Sit",  he: "לשבת" },
    {  en: "Ski",  he: "לגלוש בסקי" },
    {  en: "Sleep",  he: "לישון" },
    {  en: "Slide",  he: "להחליק" },
    {  en: "Slip",  he: "להחליק / למעוד" },
    {  en: "Slow",  he: "להאט" },
    {  en: "Smell",  he: "להריח" },
    {  en: "Smile",  he: "לחייך" },
    {  en: "Smoke",  he: "לעשן" },
    {  en: "Smooth",  he: "להחליק / להחליק" },
    {  en: "Solve",  he: "לפתור" },
    {  en: "Sort",  he: "למיין" },
    {  en: "Sound",  he: "להישמע" },
    {  en: "Speak",  he: "לדבר" },
    {  en: "Specify",  he: "לפרט / לציין במדויק" },
    {  en: "Speculate",  he: "לשער" },
    {  en: "Spend",  he: "להוציא (כסף) / לבלות (זמן)" },
    {  en: "Spread",  he: "לפרוש / להתפשט" },
    {  en: "Spring",  he: "לקפוץ" },
    {  en: "Stand",  he: "לעמוד" },
    {  en: "Start",  he: "להתחיל" },
    {  en: "State",  he: "להצהיר" },
    {  en: "Stay",  he: "להישאר" },
    {  en: "Steal",  he: "לגנוב" },
    {  en: "Step",  he: "לפסוע / לצעוד" },
    {  en: "Stick",  he: "להדביק / להידבק" },
    {  en: "Stir",  he: "לערבב" },
    {  en: "Stop",  he: "לעצור" },
    {  en: "Store",  he: "לאחסן" },
    {  en: "Research",  he: "לחקור" },
    {  en: "Resemble",  he: "להידמות ל-" },
    {  en: "Reside",  he: "לגור / להתגורר" },
    {  en: "Resist",  he: "להתנגד" },
    {  en: "Resolve",  he: "לפתור / להחליט" },
    {  en: "Respond",  he: "להגיב" },
    {  en: "Rest",  he: "לנוח" },
    {  en: "Restore",  he: "לשחזר / להחזיר" },
    {  en: "Restrict",  he: "להגביל" },
    {  en: "Result",  he: "לגרום ל-" },
    {  en: "Retain",  he: "לשמור / להחזיק" },
    {  en: "Retire",  he: "לפרוש" },
    {  en: "Retrieve",  he: "לאחזר" },
    {  en: "Return",  he: "לחזור / להחזיר" },
    {  en: "Reveal",  he: "לחשוף" },
    {  en: "Reverse",  he: "להפוך / לבטל" },
    {  en: "Review",  he: "לסקור" },
    {  en: "Revise",  he: "לשנות / לתקן" },
    {  en: "Revive",  he: "להחיות" },
    {  en: "Reward",  he: "לתגמל" },
    {  en: "Ride",  he: "לרכוב" },
    {  en: "Rise",  he: "לעלות" },
    {  en: "Risk",  he: "לסכן" },
    {  en: "Roast",  he: "לצלות" },
    {  en: "Roll",  he: "לגלגל" },
    {  en: "Rough",  he: "לגרום לחיספוס" },
    {  en: "Round",  he: "לעגל" },
    {  en: "Ruin",  he: "להרוס" },
    {  en: "Rule",  he: "לשלוט / לפקוד" },
    {  en: "Run",  he: "לרוץ / לנהל" },
    {  en: "Rush",  he: "להאיץ / למהר" },
    {  en: "Sacrifice",  he: "להקריב" },
    {  en: "Satisfy",  he: "לספק" },
    {  en: "Save",  he: "להציל / לחסוך" },
    {  en: "Say",  he: "להגיד" },
    {  en: "Scan",  he: "לסרוק" },
    {  en: "Scare",  he: "להפחיד" },
    {  en: "Schedule",  he: "לתזמן" },
    {  en: "Score",  he: "לקלוע / להשיג" },
    {  en: "Scratch",  he: "לגרד" },
    {  en: "Search",  he: "לחפש" },
    {  en: "Secure",  he: "לאבטח / להבטיח" },
    {  en: "See",  he: "לראות" },
    {  en: "Seek",  he: "לחפש" },
    {  en: "Seem",  he: "להיראות" },
    {  en: "Select",  he: "לבחור" },
    {  en: "Sell",  he: "למכור" },
    {  en: "Send",  he: "לשלוח" },
    {  en: "Sense",  he: "להרגיש / לחוש" },
    {  en: "Separate",  he: "להפריד" },
    {  en: "Question",  he: "לשאול / להטיל ספק" },
    {  en: "Quit",  he: "להפסיק / לעזוב" },
    {  en: "Raise",  he: "להרים / לגדל" },
    {  en: "Range",  he: "לנוע בטווח" },
    {  en: "Rank",  he: "לדרג" },
    {  en: "Rate",  he: "לדרג / להעריך" },
    {  en: "Reach",  he: "להגיע" },
    {  en: "React",  he: "להגיב" },
    {  en: "Read",  he: "לקרוא" },
    {  en: "Realize",  he: "להבין / להכיר ב-" },
    {  en: "Recall",  he: "להיזכר / לבטל" },
    {  en: "Receive",  he: "לקבל" },
    {  en: "Recognize",  he: "לזהות" },
    {  en: "Recommend",  he: "להמליץ" },
    {  en: "Reconstruct",  he: "לשחזר / לבנות מחדש" },
    {  en: "Record",  he: "להקליט / לתעד" },
    {  en: "Recover",  he: "להחלים / לשחזר" },
    {  en: "Recruit",  he: "לגייס" },
    {  en: "Reduce",  he: "להפחית" },
    {  en: "Refer",  he: "להפנות / להתייחס" },
    {  en: "Reflect",  he: "לשקף / להרהר" },
    {  en: "Reform",  he: "לתקן / לשנות" },
    {  en: "Refuse",  he: "לסרב" },
    {  en: "Regard",  he: "להתייחס" },
    {  en: "Register",  he: "לרשום / להירשם" },
    {  en: "Regret",  he: "להצטער" },
    {  en: "Regulate",  he: "לווסת" },
    {  en: "Reinforce",  he: "לחזק" },
    {  en: "Reject",  he: "לדחות" },
    {  en: "Relate",  he: "להתייחס / לקשר" },
    {  en: "Relax",  he: "להירגע" },
    {  en: "Release",  he: "לשחרר" },
    {  en: "Relieve",  he: "להקל" },
    {  en: "Rely",  he: "להסתמך" },
    {  en: "Remain",  he: "להישאר" },
    {  en: "Remark",  he: "להעיר / לציין" },
    {  en: "Remember",  he: "לזכור" },
    {  en: "Remind",  he: "להזכיר" },
    {  en: "Remove",  he: "להסיר" },
    {  en: "Repair",  he: "לתקן" },
    {  en: "Repeat",  he: "לחזור" },
    {  en: "Replace",  he: "להחליף" },
    {  en: "Reply",  he: "להשיב" },
    {  en: "Report",  he: "לדווח" },
    {  en: "Represent",  he: "לייצג" },
    {  en: "Reproduce",  he: "לשכפל / להתרבות" },
    {  en: "Request",  he: "לבקש" },
    {  en: "Require",  he: "לדרוש" },
    {  en: "Rescue",  he: "להציל" },
    {  en: "Participate",  he: "להשתתף" },
    {  en: "Pass",  he: "לעבור / למסור" },
    {  en: "Perform",  he: "לבצע" },
    {  en: "Permit",  he: "להרשות" },
    {  en: "Persuade",  he: "לשכנע" },
    {  en: "Phone",  he: "לטלפן" },
    {  en: "Pick",  he: "לבחור / לקטוף" },
    {  en: "Place",  he: "להניח / למקם" },
    {  en: "Plan",  he: "לתכנן" },
    {  en: "Plant",  he: "לשתול" },
    {  en: "Play",  he: "לשחק" },
    {  en: "Please",  he: "לרצות / בבקשה" },
    {  en: "Point",  he: "להצביע / לציין" },
    {  en: "Possess",  he: "להחזיק ב-" },
    {  en: "Post",  he: "לפרסם / לשלוח בדואר" },
    {  en: "Practice",  he: "לתרגל" },
    {  en: "Praise",  he: "לשבח" },
    {  en: "Predict",  he: "לחזות" },
    {  en: "Prefer",  he: "להעדיף" },
    {  en: "Prepare",  he: "להכין" },
    {  en: "Prescribe",  he: "לרשום (תרופה)" },
    {  en: "Present",  he: "להציג" },
    {  en: "Preserve",  he: "לשמר" },
    {  en: "Preside",  he: "לנהל ישיבה" },
    {  en: "Press",  he: "ללחוץ" },
    {  en: "Presume",  he: "להניח" },
    {  en: "Pretend",  he: "להעמיד פנים" },
    {  en: "Prevail",  he: "לגבור / לנצח" },
    {  en: "Prevent",  he: "למנוע" },
    {  en: "Print",  he: "להדפיס" },
    {  en: "Proceed",  he: "להמשיך" },
    {  en: "Process",  he: "לעבד" },
    {  en: "Produce",  he: "לייצר" },
    {  en: "Progress",  he: "להתקדם" },
    {  en: "Prohibit",  he: "לאסור" },
    {  en: "Project",  he: "להקרין / לתכנן" },
    {  en: "Promise",  he: "להבטיח" },
    {  en: "Promote",  he: "לקדם" },
    {  en: "Propose",  he: "להציע" },
    {  en: "Protect",  he: "להגן" },
    {  en: "Prove",  he: "להוכיח" },
    {  en: "Provide",  he: "לספק" },
    {  en: "Publish",  he: "לפרסם" },
    {  en: "Pull",  he: "למשוך" },
    {  en: "Punish",  he: "להעניש" },
    {  en: "Purchase",  he: "לרכוש" },
    {  en: "Pursue",  he: "לרדוף / לשאוף" },
    {  en: "Push",  he: "לדחוף" },
    {  en: "Put",  he: "לשים" },
    {  en: "Qualify",  he: "להכשיר / להסמיך" },
    {  en: "Maintain",  he: "לתחזק / לשמר" },
    {  en: "Make",  he: "להכין / לעשות" },
    {  en: "Manage",  he: "לנהל" },
    {  en: "Manifest",  he: "להתגלות / להפגין" },
    {  en: "Manipulate",  he: "לתמרן" },
    {  en: "Mark",  he: "לסמן" },
    {  en: "Marry",  he: "להתחתן" },
    {  en: "Match",  he: "להתאים" },
    {  en: "Matter",  he: "להיות חשוב" },
    {  en: "Measure",  he: "למדוד" },
    {  en: "Mediate",  he: "לתווך" },
    {  en: "Meet",  he: "לפגוש" },
    {  en: "Melt",  he: "להימס" },
    {  en: "Mention",  he: "להזכיר" },
    {  en: "Merge",  he: "למזג" },
    {  en: "Migrate",  he: "להגר" },
    {  en: "Mind",  he: "לאכפת ל-" },
    {  en: "Minimize",  he: "למזער" },
    {  en: "Miss",  he: "להתגעגע / לפספס" },
    {  en: "Mix",  he: "לערבב" },
    {  en: "Monitor",  he: "לנטר" },
    {  en: "Motivate",  he: "להניע" },
    {  en: "Move",  he: "לזוז / להזיז" },
    {  en: "Multiply",  he: "להכפיל" },
    {  en: "Murder",  he: "לרצוח" },
    {  en: "Navigate",  he: "לנווט" },
    {  en: "Need",  he: "לצרוך / להזדקק" },
    {  en: "Neglect",  he: "להזניח" },
    {  en: "Negotiate",  he: "לנהל משא ומתן" },
    {  en: "Note",  he: "לציין / לרשום" },
    {  en: "Notice",  he: "להבחין" },
    {  en: "Notify",  he: "להודיע" },
    {  en: "Obey",  he: "לציית" },
    {  en: "Object",  he: "להתנגד" },
    {  en: "Observe",  he: "להתבונן / לצפות" },
    {  en: "Obtain",  he: "להשיג" },
    {  en: "Occur",  he: "להתרחש" },
    {  en: "Offend",  he: "להעליב" },
    {  en: "Offer",  he: "להציע" },
    {  en: "Open",  he: "לפתוח" },
    {  en: "Operate",  he: "להפעיל / לתפעל" },
    {  en: "Oppose",  he: "להתנגד" },
    {  en: "Order",  he: "להזמין / לפקוד" },
    {  en: "Organize",  he: "לארגן" },
    {  en: "Originate",  he: "לנבוע / ליזום" },
    {  en: "Overcome",  he: "להתגבר" },
    {  en: "Oversee",  he: "לפקח" },
    {  en: "Own",  he: "להיות בעלים של" },
    {  en: "Paint",  he: "לצבוע" },
    {  en: "Instruct",  he: "להדריך / להורות" },
    {  en: "Integrate",  he: "לשלב" },
    {  en: "Intend",  he: "להתכוון" },
    {  en: "Interact",  he: "לקיים אינטראקציה" },
    {  en: "Interpret",  he: "לפרש" },
    {  en: "Intervene",  he: "להתערב" },
    {  en: "Introduce",  he: "להציג / להכיר" },
    {  en: "Invent",  he: "להמציא" },
    {  en: "Invest",  he: "להשקיע" },
    {  en: "Investigate",  he: "לחקור" },
    {  en: "Involve",  he: "לערב" },
    {  en: "Issue",  he: "להוציא / להנפיק" },
    {  en: "Join",  he: "להצטרף" },
    {  en: "Judge",  he: "לשפוט" },
    {  en: "Jump",  he: "לקפוץ" },
    {  en: "Justify",  he: "להצדיק" },
    {  en: "Keep",  he: "לשמור" },
    {  en: "Kick",  he: "לבעוט" },
    {  en: "Kill",  he: "להרוג" },
    {  en: "Kiss",  he: "לנשק" },
    {  en: "Knock",  he: "לדפוק" },
    {  en: "Know",  he: "לדעת" },
    {  en: "Label",  he: "לתייג" },
    {  en: "Lack",  he: "לחסור" },
    {  en: "Land",  he: "לנחות" },
    {  en: "Last",  he: "להימשך / לאחרון" },
    {  en: "Laugh",  he: "לצחוק" },
    {  en: "Launch",  he: "להשיק" },
    {  en: "Lead",  he: "להוביל" },
    {  en: "Learn",  he: "ללמוד" },
    {  en: "Leave",  he: "לעזוב" },
    {  en: "Lend",  he: "להלוות" },
    {  en: "Let",  he: "לתת ל-" },
    {  en: "Level",  he: "ליישר / לרמת" },
    {  en: "Lie",  he: "לשכב / לשקר" },
    {  en: "Lift",  he: "להרים" },
    {  en: "Light",  he: "להאיר" },
    {  en: "Like",  he: "לאהוב / כמו" },
    {  en: "Limit",  he: "להגביל" },
    {  en: "Line",  he: "ליישר / לשרטט קו" },
    {  en: "Link",  he: "לקשר" },
    {  en: "Listen",  he: "להקשיב" },
    {  en: "Live",  he: "לחיות" },
    {  en: "Load",  he: "לטעון" },
    {  en: "Locate",  he: "לאתר" },
    {  en: "Lock",  he: "לנעול" },
    {  en: "Look",  he: "להסתכל" },
    {  en: "Lose",  he: "לאבד" },
    {  en: "Love",  he: "לאהוב" },
    {  en: "Found",  he: "לייסד" },
    {  en: "Frame",  he: "למסגר" },
    {  en: "Fulfill",  he: "להגשים / למלא" },
    {  en: "Function",  he: "לתפקד" },
    {  en: "Gather",  he: "לאסוף" },
    {  en: "Generate",  he: "לייצר" },
    {  en: "Get",  he: "לקבל" },
    {  en: "Give",  he: "לתת" },
    {  en: "Go",  he: "ללכת" },
    {  en: "Govern",  he: "למשול" },
    {  en: "Grant",  he: "להעניק" },
    {  en: "Grow",  he: "לגדול" },
    {  en: "Guarantee",  he: "להבטיח" },
    {  en: "Guide",  he: "להדריך" },
    {  en: "Handle",  he: "לטפל" },
    {  en: "Happen",  he: "לקרות" },
    {  en: "Harm",  he: "להזיק" },
    {  en: "Head",  he: "לעמוד בראש / ללכת לכיוון" },
    {  en: "Hear",  he: "לשמוע" },
    {  en: "Help",  he: "לעזור" },
    {  en: "Hesitate",  he: "להסס" },
    {  en: "Hide",  he: "להתחבא / להחביא" },
    {  en: "Highlight",  he: "להדגיש" },
    {  en: "Hire",  he: "לשכור" },
    {  en: "Hit",  he: "להכות / לפגוע" },
    {  en: "Hold",  he: "להחזיק" },
    {  en: "Hope",  he: "לקוות" },
    {  en: "Identify",  he: "לזהות" },
    {  en: "Ignore",  he: "להתעלם" },
    {  en: "Illustrate",  he: "להמחיש" },
    {  en: "Imagine",  he: "לדמיין" },
    {  en: "Impact",  he: "להשפיע" },
    {  en: "Implement",  he: "ליישם" },
    {  en: "Imply",  he: "לרמוז" },
    {  en: "Import",  he: "לייבא" },
    {  en: "Impress",  he: "להרשים" },
    {  en: "Improve",  he: "לשפר" },
    {  en: "Include",  he: "לכלול" },
    {  en: "Increase",  he: "להגדיל" },
    {  en: "Indicate",  he: "לציין" },
    {  en: "Influence",  he: "להשפיע" },
    {  en: "Inform",  he: "להודיע" },
    {  en: "Initiate",  he: "ליזום" },
    {  en: "Inject",  he: "להזריק" },
    {  en: "Injure",  he: "לפגוע / לפצוע" },
    {  en: "Innovate",  he: "לחדש" },
    {  en: "Inspect",  he: "לבחון / לפקח" },
    {  en: "Inspire",  he: "להשראה" },
    {  en: "Install",  he: "להתקין" },
    {  en: "Enable",  he: "לאפשר" },
    {  en: "Encourage",  he: "לעודד" },
    {  en: "End",  he: "לסיים" },
    {  en: "Enforce",  he: "לאכוף" },
    {  en: "Engage",  he: "לעסוק / לערב" },
    {  en: "Enhance",  he: "לשפר" },
    {  en: "Enjoy",  he: "ליהנות" },
    {  en: "Ensure",  he: "להבטיח" },
    {  en: "Enter",  he: "להיכנס" },
    {  en: "Establish",  he: "להקים" },
    {  en: "Estimate",  he: "להעריך" },
    {  en: "Evaluate",  he: "להעריך" },
    {  en: "Examine",  he: "לבחון" },
    {  en: "Exceed",  he: "לחרוג / לעלות על" },
    {  en: "Exclude",  he: "להוציא / למנוע" },
    {  en: "Execute",  he: "לבצע" },
    {  en: "Exist",  he: "להתקיים" },
    {  en: "Expand",  he: "להתרחב" },
    {  en: "Expect",  he: "לצפות" },
    {  en: "Experience",  he: "לחוות" },
    {  en: "Explain",  he: "להסביר" },
    {  en: "Explore",  he: "לחקור" },
    {  en: "Expose",  he: "לחשוף" },
    {  en: "Express",  he: "לבטא" },
    {  en: "Extend",  he: "להאריך / להרחיב" },
    {  en: "Face",  he: "להתמודד" },
    {  en: "Facilitate",  he: "להקל" },
    {  en: "Fail",  he: "לכישלון" },
    {  en: "Fall",  he: "ליפול" },
    {  en: "Fear",  he: "לפחד" },
    {  en: "Feature",  he: "להציג / לאפיין" },
    {  en: "Feed",  he: "להאכיל" },
    {  en: "Feel",  he: "להרגיש" },
    {  en: "Fight",  he: "להילחם" },
    {  en: "Figure",  he: "להבין / לחשב" },
    {  en: "Fill",  he: "למלא" },
    {  en: "Finance",  he: "לממן" },
    {  en: "Find",  he: "למצוא" },
    {  en: "Finish",  he: "לסיים" },
    {  en: "Fit",  he: "להתאים" },
    {  en: "Fix",  he: "לתקן" },
    {  en: "Flee",  he: "לברוח" },
    {  en: "Float",  he: "לצוף" },
    {  en: "Flow",  he: "לזרום" },
    {  en: "Focus",  he: "להתמקד" },
    {  en: "Follow",  he: "לעקוב" },
    {  en: "Force",  he: "לאלץ" },
    {  en: "Forecast",  he: "לחזות" },
    {  en: "Form",  he: "ליצור / לעצב" },
    {  en: "Dare",  he: "להעז" },
    {  en: "Date",  he: "לתארך" },
    {  en: "Deal",  he: "לעסוק / להתמודד" },
    {  en: "Debate",  he: "להתווכח" },
    {  en: "Decide",  he: "להחליט" },
    {  en: "Declare",  he: "להכריז" },
    {  en: "Decline",  he: "לסרב / לרדת" },
    {  en: "Decrease",  he: "להפחית" },
    {  en: "Defend",  he: "להגן" },
    {  en: "Define",  he: "להגדיר" },
    {  en: "Delay",  he: "לעכב" },
    {  en: "Deliver",  he: "למסור" },
    {  en: "Demand",  he: "לדרוש" },
    {  en: "Demonstrate",  he: "להדגים" },
    {  en: "Deny",  he: "להכחיש" },
    {  en: "Depend",  he: "להיות תלוי ב-" },
    {  en: "Depict",  he: "לתאר" },
    {  en: "Deposit",  he: "להפקיד" },
    {  en: "Derive",  he: "לגזור / לנבוע" },
    {  en: "Describe",  he: "לתאר" },
    {  en: "Deserve",  he: "להיות ראוי ל-" },
    {  en: "Destroy",  he: "להרוס" },
    {  en: "Detect",  he: "לגלות" },
    {  en: "Determine",  he: "לקבוע" },
    {  en: "Develop",  he: "לפתח" },
    {  en: "Devote",  he: "להקדיש" },
    {  en: "Differentiate",  he: "להבדיל" },
    {  en: "Direct",  he: "לכוון / לנהל" },
    {  en: "Disagree",  he: "לא להסכים" },
    {  en: "Disappear",  he: "להיעלם" },
    {  en: "Discover",  he: "לגלות" },
    {  en: "Discuss",  he: "לדון" },
    {  en: "Distinguish",  he: "להבחין" },
    {  en: "Distribute",  he: "להפיץ" },
    {  en: "Divide",  he: "לחלק" },
    {  en: "Dominate",  he: "לשלוט" },
    {  en: "Double",  he: "להכפיל" },
    {  en: "Drag",  he: "לגרור" },
    {  en: "Draw",  he: "לצייר / למשוך" },
    {  en: "Drive",  he: "לנהוג" },
    {  en: "Drop",  he: "להפיל / לרדת" },
    {  en: "Earn",  he: "להרוויח" },
    {  en: "Eat",  he: "לאכול" },
    {  en: "Edit",  he: "לערוך" },
    {  en: "Educate",  he: "לחנך" },
    {  en: "Elect",  he: "לבחור (בבחירות)" },
    {  en: "Eliminate",  he: "לחסל" },
    {  en: "Embrace",  he: "לחבק / לאמץ" },
    {  en: "Emerge",  he: "לצוף / להופיע" },
    {  en: "Emphasize",  he: "להדגיש" },
    {  en: "Attend",  he: "להשתתף" },
    {  en: "Attract",  he: "למשוך" },
    {  en: "Avoid",  he: "להימנע" },
    {  en: "Base",  he: "לבסס" },
    {  en: "Beat",  he: "להביס / להכות" },
    {  en: "Benefit",  he: "להועיל" },
    {  en: "Blame",  he: "להאשים" },
    {  en: "Borrow",  he: "ללוות" },
    {  en: "Bother",  he: "להטריד" },
    {  en: "Bridge",  he: "לגשר" },
    {  en: "Cancel",  he: "לבטל" },
    {  en: "Capture",  he: "ללכוד" },
    {  en: "Cause",  he: "לגרום" },
    {  en: "Challenge",  he: "לאתגר" },
    {  en: "Characterize",  he: "לאפיין" },
    {  en: "Claim",  he: "לטעון" },
    {  en: "Collect",  he: "לאסוף" },
    {  en: "Combine",  he: "לשלב" },
    {  en: "Command",  he: "לפקד / לפקוד" },
    {  en: "Comment",  he: "להגיב" },
    {  en: "Commit",  he: "להתחייב" },
    {  en: "Communicate",  he: "לתקשר" },
    {  en: "Compete",  he: "להתחרות" },
    {  en: "Complain",  he: "להתלונן" },
    {  en: "Complete",  he: "להשלים" },
    {  en: "Comply",  he: "לציית" },
    {  en: "Concentrate",  he: "להתרכז" },
    {  en: "Concern",  he: "לדאוג / לעניין" },
    {  en: "Conclude",  he: "להסיק" },
    {  en: "Conduct",  he: "לערוך / לנהל" },
    {  en: "Confirm",  he: "לאשר" },
    {  en: "Connect",  he: "לחבר" },
    {  en: "Consider",  he: "לשקול" },
    {  en: "Consist",  he: "להיות מורכב מ-" },
    {  en: "Construct",  he: "לבנות" },
    {  en: "Consult",  he: "להתייעץ" },
    {  en: "Consume",  he: "לצרוך" },
    {  en: "Contain",  he: "להכיל" },
    {  en: "Contribute",  he: "לתרום" },
    {  en: "Convert",  he: "להמיר" },
    {  en: "Convince",  he: "לשכנע" },
    {  en: "Cope",  he: "להתמודד" },
    {  en: "Correct",  he: "לתקן" },
    {  en: "Cost",  he: "לעלות (במחיר)" },
    {  en: "Count",  he: "לספור" },
    {  en: "Cover",  he: "לכסות" },
    {  en: "Crash",  he: "להתרסק" },
    {  en: "Criticize",  he: "לבקר" },
    {  en: "Cross",  he: "לחצות" },
    {  en: "Damage",  he: "להזיק" },
    {  en: "Suggest",  he: "להציע" },
    {  en: "Support",  he: "לתמוך" },
    {  en: "Suppose",  he: "להניח" },
    {  en: "Survive",  he: "לשרוד" },
    {  en: "Take",  he: "לקחת" },
    {  en: "Talk",  he: "לדבר" },
    {  en: "Teach",  he: "ללמד" },
    {  en: "Tell",  he: "לספר" },
    {  en: "Tend",  he: "לנטות ל-" },
    {  en: "Test",  he: "לבחון / לבדוק" },
    {  en: "Thank",  he: "להודות" },
    {  en: "Think",  he: "לחשוב" },
    {  en: "Threaten",  he: "לאיים" },
    {  en: "Throw",  he: "לזרוק" },
    {  en: "Touch",  he: "לגעת" },
    {  en: "Train",  he: "לאמן" },
    {  en: "Treat",  he: "לטפל / להתייחס" },
    {  en: "Travel",  he: "לטייל" },
    {  en: "Try",  he: "לנסות" },
    {  en: "Turn",  he: "לפנות / להסתובב" },
    {  en: "Understand",  he: "להבין" },
    {  en: "Use",  he: "להשתמש" },
    {  en: "Vary",  he: "להשתנות" },
    {  en: "View",  he: "לצפות / לראות" },
    {  en: "Visit",  he: "לבקר" },
    {  en: "Vote",  he: "להצביע" },
    {  en: "Wait",  he: "לחכות" },
    {  en: "Wake",  he: "להתעורר" },
    {  en: "Walk",  he: "ללכת" },
    {  en: "Want",  he: "לרצות" },
    {  en: "Warn",  he: "להזהיר" },
    {  en: "Wash",  he: "לשטוף" },
    {  en: "Watch",  he: "לצפות" },
    {  en: "Wear",  he: "ללבוש" },
    {  en: "Win",  he: "לנצח" },
    {  en: "Wish",  he: "לאחל" },
    {  en: "Wonder",  he: "לתהות" },
    {  en: "Work",  he: "לעבוד" },
    {  en: "Worry",  he: "לדאוג" },
    {  en: "Write",  he: "לכתוב" },
    {  en: "Admit",  he: "להודות" },
    {  en: "Adopt",  he: "לאמץ" },
    {  en: "Advise",  he: "לייעץ" },
    {  en: "Afford",  he: "להרשות לעצמו" },
    {  en: "Aim",  he: "לכוון" },
    {  en: "Allow",  he: "לאפשר" },
    {  en: "Announce",  he: "להודיע" },
    {  en: "Approve",  he: "לאשר" },
    {  en: "Arrange",  he: "לארגן" },
    {  en: "Avoid",  he: "להימנע" },
    {  en: "Receive",  he: "לקבל" },
    {  en: "Recognize",  he: "לזהות" },
    {  en: "Record",  he: "להקליט / לתעד" },
    {  en: "Reduce",  he: "להפחית" },
    {  en: "Refer",  he: "להפנות / להתייחס" },
    {  en: "Reflect",  he: "לשקף" },
    {  en: "Refuse",  he: "לסרב" },
    {  en: "Regard",  he: "להתייחס / להתחשב" },
    {  en: "Release",  he: "לשחרר" },
    {  en: "Remain",  he: "להישאר" },
    {  en: "Remember",  he: "לזכור" },
    {  en: "Remove",  he: "להסיר" },
    {  en: "Repeat",  he: "לחזור" },
    {  en: "Replace",  he: "להחליף" },
    {  en: "Reply",  he: "להשיב" },
    {  en: "Report",  he: "לדווח" },
    {  en: "Represent",  he: "לייצג" },
    {  en: "Require",  he: "לדרוש" },
    {  en: "Rest",  he: "לנוח" },
    {  en: "Result",  he: "לגרום ל-" },
    {  en: "Return",  he: "לחזור / להחזיר" },
    {  en: "Reveal",  he: "לחשוף" },
    {  en: "Rise",  he: "לעלות" },
    {  en: "Roll",  he: "לגלגל" },
    {  en: "Run",  he: "לרוץ" },
    {  en: "Save",  he: "להציל / לחסוך" },
    {  en: "Say",  he: "להגיד" },
    {  en: "See",  he: "לראות" },
    {  en: "Seek",  he: "לחפש" },
    {  en: "Seem",  he: "להיראות" },
    {  en: "Sell",  he: "למכור" },
    {  en: "Send",  he: "לשלוח" },
    {  en: "Set",  he: "להגדיר / לקבוע" },
    {  en: "Share",  he: "לשתף" },
    {  en: "Shoot",  he: "לירות" },
    {  en: "Show",  he: "להראות" },
    {  en: "Shrink",  he: "להתכווץ" },
    {  en: "Shut",  he: "לסגור" },
    {  en: "Sing",  he: "לשיר" },
    {  en: "Sit",  he: "לשבת" },
    {  en: "Sleep",  he: "לישון" },
    {  en: "Smile",  he: "לחייך" },
    {  en: "Solve",  he: "לפתור" },
    {  en: "Sound",  he: "להישמע" },
    {  en: "Speak",  he: "לדבר" },
    {  en: "Spend",  he: "להוציא / לבלות" },
    {  en: "Stand",  he: "לעמוד" },
    {  en: "Start",  he: "להתחיל" },
    {  en: "State",  he: "להצהיר" },
    {  en: "Stay",  he: "להישאר" },
    {  en: "Laugh",  he: "לצחוק" },
    {  en: "Lead",  he: "להוביל" },
    {  en: "Learn",  he: "ללמוד" },
    {  en: "Leave",  he: "לעזוב" },
    {  en: "Lie",  he: "לשכב / לשקר" },
    {  en: "Like",  he: "לאהוב / כמו" },
    {  en: "Listen",  he: "להקשיב" },
    {  en: "Live",  he: "לחיות" },
    {  en: "Look",  he: "להסתכל" },
    {  en: "Lose",  he: "לאבד" },
    {  en: "Love",  he: "לאהוב" },
    {  en: "Make",  he: "להכין" },
    {  en: "Manage",  he: "לנהל" },
    {  en: "Mark",  he: "לסמן" },
    {  en: "Meet",  he: "לפגוש" },
    {  en: "Mention",  he: "להזכיר" },
    {  en: "Mind",  he: "לאכפת ל-" },
    {  en: "Miss",  he: "להתגעגע / לפספס" },
    {  en: "Move",  he: "לזוז" },
    {  en: "Need",  he: "צריך" },
    {  en: "Notice",  he: "להבחין" },
    {  en: "Obtain",  he: "להשיג" },
    {  en: "Offer",  he: "להציע" },
    {  en: "Open",  he: "לפתוח" },
    {  en: "Order",  he: "להזמין / לפקוד" },
    {  en: "Overcome",  he: "להתגבר" },
    {  en: "Own",  he: "להיות בעלים של" },
    {  en: "Pass",  he: "לעבור / למסור" },
    {  en: "Perform",  he: "לבצע" },
    {  en: "Pick",  he: "לבחור / לקטוף" },
    {  en: "Place",  he: "להניח / למקם" },
    {  en: "Plan",  he: "לתכנן" },
    {  en: "Play",  he: "לשחק" },
    {  en: "Point",  he: "להצביע / לציין" },
    {  en: "Prepare",  he: "להכין" },
    {  en: "Present",  he: "להציג" },
    {  en: "Press",  he: "ללחוץ" },
    {  en: "Prevent",  he: "למנוע" },
    {  en: "Produce",  he: "לייצר" },
    {  en: "Promote",  he: "לקדם" },
    {  en: "Protect",  he: "להגן" },
    {  en: "Provide",  he: "לספק" },
    {  en: "Publish",  he: "לפרסם" },
    {  en: "Pull",  he: "למשוך" },
    {  en: "Push",  he: "לדחוף" },
    {  en: "Put",  he: "לשים" },
    {  en: "Reach",  he: "להגיע" },
    {  en: "Read",  he: "לקרוא" },
    {  en: "Realize",  he: "להבין / להכיר ב-" },
    {  en: "Pass",  he: "לעבור / למסור" },
    {  en: "Sell",  he: "למכור" },
    {  en: "Require",  he: "לדרוש" },
    {  en: "Report",  he: "לדווח" },
    {  en: "Decide",  he: "להחליט" },
    {  en: "Pull",  he: "למשוך" },
    {  en: "Return",  he: "לחזור / להחזיר" },
    {  en: "Explain",  he: "להסביר" },
    {  en: "Hope",  he: "לקוות" },
    {  en: "Develop",  he: "לפתח" },
    {  en: "Carry",  he: "לשאת" },
    {  en: "Break",  he: "לשבור" },
    {  en: "Receive",  he: "לקבל" },
    {  en: "Agree",  he: "להסכים" },
    {  en: "Support",  he: "לתמוך" },
    {  en: "Hit",  he: "להכות" },
    {  en: "Relate",  he: "להתייחס / לקשר" },
    {  en: "Discuss",  he: "לדון" },
    {  en: "Prove",  he: "להוכיח" },
    {  en: "Catch",  he: "לתפוס" },
    {  en: "Cause",  he: "לגרום" },
    {  en: "Charge",  he: "לחייב / להטעין" },
    {  en: "Claim",  he: "לטעון / לתבוע" },
    {  en: "Compare",  he: "להשוות" },
    {  en: "Control",  he: "לשלוט" },
    {  en: "Deal",  he: "לעסוק / להתמודד" },
    {  en: "Design",  he: "לעצב" },
    {  en: "Determine",  he: "לקבוע" },
    {  en: "Draw",  he: "לצייר" },
    {  en: "Enjoy",  he: "ליהנות" },
    {  en: "Establish",  he: "להקים" },
    {  en: "Exist",  he: "להתקיים" },
    {  en: "Expand",  he: "להתרחב" },
    {  en: "Expect",  he: "לצפות" },
    {  en: "Experience",  he: "לחוות" },
    {  en: "Express",  he: "לבטא" },
    {  en: "Face",  he: "להתמודד" },
    {  en: "Fail",  he: "לכישלון" },
    {  en: "Fit",  he: "להתאים" },
    {  en: "Form",  he: "ליצור / לעצב" },
    {  en: "Gain",  he: "להשיג" },
    {  en: "Generate",  he: "לייצר" },
    {  en: "Handle",  he: "לטפל" },
    {  en: "Identify",  he: "לזהות" },
    {  en: "Imagine",  he: "לדמיין" },
    {  en: "Indicate",  he: "לציין" },
    {  en: "Invest",  he: "להשקיע" },
    {  en: "Join",  he: "להצטרף" },
    {  en: "Judge",  he: "לשפוט" },
    {  en: "Keep",  he: "לשמור" },
    {  en: "Run",  he: "לרוץ" },
    {  en: "Move",  he: "לזוז" },
    {  en: "Like",  he: "לאהוב / כמו" },
    {  en: "Live",  he: "לחיות" },
    {  en: "Believe",  he: "להאמין" },
    {  en: "Hold",  he: "להחזיק" },
    {  en: "Bring",  he: "להביא" },
    {  en: "Happen",  he: "לקרות" },
    {  en: "Write",  he: "לכתוב" },
    {  en: "Provide",  he: "לספק" },
    {  en: "Sit",  he: "לשבת" },
    {  en: "Stand",  he: "לעמוד" },
    {  en: "Lose",  he: "לאבד" },
    {  en: "Pay",  he: "לשלם" },
    {  en: "Meet",  he: "לפגוש" },
    {  en: "Include",  he: "לכלול" },
    {  en: "Continue",  he: "להמשיך" },
    {  en: "Set",  he: "להגדיר / לקבוע" },
    {  en: "Learn",  he: "ללמוד" },
    {  en: "Change",  he: "לשנות" },
    {  en: "Lead",  he: "להוביל" },
    {  en: "Understand",  he: "להבין" },
    {  en: "Watch",  he: "לצפות" },
    {  en: "Follow",  he: "לעקוב" },
    {  en: "Stop",  he: "לעצור" },
    {  en: "Create",  he: "ליצור" },
    {  en: "Speak",  he: "לדבר" },
    {  en: "Read",  he: "לקרוא" },
    {  en: "Allow",  he: "לאפשר" },
    {  en: "Add",  he: "להוסיף" },
    {  en: "Spend",  he: "להוציא / לבלות" },
    {  en: "Grow",  he: "לגדול" },
    {  en: "Open",  he: "לפתוח" },
    {  en: "Walk",  he: "ללכת" },
    {  en: "Win",  he: "לנצח" },
    {  en: "Offer",  he: "להציע" },
    {  en: "Remember",  he: "לזכור" },
    {  en: "Consider",  he: "לשקול" },
    {  en: "Appear",  he: "להופיע" },
    {  en: "Buy",  he: "לקנות" },
    {  en: "Serve",  he: "לשרת" },
    {  en: "Die",  he: "למות" },
    {  en: "Send",  he: "לשלוח" },
    {  en: "Build",  he: "לבנות" },
    {  en: "Stay",  he: "להישאר" },
    {  en: "Fall",  he: "ליפול" },
    {  en: "Cut",  he: "לחתוך" },
    {  en: "Receive",  he: "לקבל" },
    {  en: "Suggest",  he: "להציע" },
    {  en: "Raise",  he: "להרים / לגדל" },
    {  en: "Look",  he: "להסתכל" },
    {  en: "See",  he: "לראות" },
    {  en: "Watch",  he: "לצפות" },
    {  en: "Hear",  he: "לשמוע" },
    {  en: "Listen",  he: "להקשיב" },
    {  en: "Feel",  he: "להרגיש" },
    {  en: "Touch",  he: "לגעת" },
    {  en: "Taste",  he: "לטעום" },
    {  en: "Smell",  he: "להריח" },
    {  en: "Live",  he: "לחיות" },
    {  en: "Die",  he: "למות" },
    {  en: "Be",  he: "להיות" },
    {  en: "Have",  he: "יש ל-" },
    {  en: "Do",  he: "לעשות" },
    {  en: "Say",  he: "להגיד" },
    {  en: "Go",  he: "ללכת" },
    {  en: "Come",  he: "לבוא" },
    {  en: "Get",  he: "לקבל" },
    {  en: "Make",  he: "להכין" },
    {  en: "Know",  he: "לדעת" },
    {  en: "Think",  he: "לחשוב" },
    {  en: "Take",  he: "לקחת" },
    {  en: "See",  he: "לראות" },
    {  en: "Come",  he: "לבוא" },
    {  en: "Want",  he: "לרצות" },
    {  en: "Use",  he: "להשתמש" },
    {  en: "Find",  he: "למצוא" },
    {  en: "Give",  he: "לתת" },
    {  en: "Tell",  he: "לספר" },
    {  en: "Work",  he: "לעבוד" },
    {  en: "Call",  he: "להתקשר" },
    {  en: "Try",  he: "לנסות" },
    {  en: "Ask",  he: "לשאול" },
    {  en: "Need",  he: "צריך" },
    {  en: "Feel",  he: "להרגיש" },
    {  en: "Become",  he: "להפוך ל-" },
    {  en: "Leave",  he: "לעזוב" },
    {  en: "Put",  he: "לשים" },
    {  en: "Mean",  he: "להתכוון" },
    {  en: "Keep",  he: "לשמור" },
    {  en: "Let",  he: "לתת ל-" },
    {  en: "Begin",  he: "להתחיל" },
    {  en: "Seem",  he: "להיראות" },
    {  en: "Help",  he: "לעזור" },
    {  en: "Talk",  he: "לדבר" },
    {  en: "Turn",  he: "לפנות" },
    {  en: "Start",  he: "להתחיל" },
    {  en: "Show",  he: "להראות" },
    {  en: "Hear",  he: "לשמוע" },
    {  en: "Play",  he: "לשחק" },
    {  en: "Live",  he: "לחיות" },
    {  en: "Die",  he: "למות" },
    {  en: "Grow",  he: "לגדול" },
    {  en: "Change",  he: "לשנות" },
    {  en: "Become",  he: "להפוך ל-" },
    {  en: "Start",  he: "להתחיל" },
    {  en: "End",  he: "לסיים" },
    {  en: "Follow",  he: "לעקוב" },
    {  en: "Lead",  he: "להוביל" },
    {  en: "Hold",  he: "להחזיק" },
    {  en: "Keep",  he: "לשמור" },
    {  en: "Leave",  he: "לעזוב" },
    {  en: "Stay",  he: "להישאר" },
    {  en: "Move",  he: "לזוז" },
    {  en: "Turn",  he: "לפנות / להסתובב" },
    {  en: "Walk",  he: "ללכת" },
    {  en: "Run",  he: "לרוץ" },
    {  en: "Jump",  he: "לקפוץ" },
    {  en: "Sit",  he: "לשבת" },
    {  en: "Stand",  he: "לעמוד" },
    {  en: "Lie",  he: "לשכב" },
    {  en: "Sleep",  he: "לישון" },
    {  en: "Wake up",  he: "להתעורר" },
    {  en: "Dream",  he: "לחלום" },
    {  en: "Laugh",  he: "לצחוק" },
    {  en: "Cry",  he: "לבכות" },
    {  en: "Smile",  he: "לחייך" },
    {  en: "Frown",  he: "לקמט מצח" },
    {  en: "Sing",  he: "לשיר" },
    {  en: "Dance",  he: "לרקוד" },
    {  en: "Play",  he: "לשחק" },
    {  en: "Work",  he: "לעבוד" },
    {  en: "Study",  he: "ללמוד" },
    {  en: "Teach",  he: "ללמד" },
    {  en: "Learn",  he: "ללמוד" },
    {  en: "Read",  he: "לקרוא" },
    {  en: "Write",  he: "לכתוב" },
    {  en: "Draw",  he: "לצייר" },
    {  en: "Paint",  he: "לצבוע / לצייר" },
    {  en: "Cook",  he: "לבשל" },
    {  en: "Bake",  he: "לאפות" },
    {  en: "Clean",  he: "לנקות" },
    {  en: "Wash",  he: "לשטוף" },
    {  en: "Drive",  he: "לנהוג" },
    {  en: "Ride",  he: "לרכוב" },
    {  en: "Fly",  he: "לטוס" },
    {  en: "Swim",  he: "לשחות" },
    {  en: "Walk",  he: "ללכת" },
    {  en: "Run",  he: "לרוץ" },
    {  en: "Jump",  he: "לקפוץ" },
{  en: "Need",  he: "צריך" },
    {  en: "Use",  he: "להשתמש" },
    {  en: "Make",  he: "להכין" },
    {  en: "Do",  he: "לעשות" },
    {  en: "Go",  he: "ללכת / לנסוע" },
    {  en: "Come",  he: "לבוא" },
    {  en: "Get",  he: "לקבל" },
    { " en": "Give", " he": "לתת" },
    {  en: "Take",  he: "לקחת" },
    {  en: "Bring",  he: "להביא" },
    {  en: "Find",  he: "למצוא" },
    {  en: "Lose",  he: "לאבד" },
    {  en: "Buy",  he: "לקנות" },
    {  en: "Sell",  he: "למכור" },
    {  en: "Pay",  he: "לשלם" },
    {  en: "Win",  he: "לנצח" },
    {  en: "Lose",  he: "להפסיד" },
    {  en: "Start",  he: "להתחיל" },
    {  en: "Stop",  he: "לעצור" },
    {  en: "Finish",  he: "לסיים" },
    {  en: "Open",  he: "לפתוח" },
    {  en: "Close",  he: "לסגור" },
    {  en: "Push",  he: "לדחוף" },
    {  en: "Pull",  he: "למשוך" },
    {  en: "Cut",  he: "לחתוך" },
    {  en: "Break",  he: "לשבור" },
    {  en: "Build",  he: "לבנות" },
    {  en: "Destroy",  he: "להרוס" },
    {  en: "Create",  he: "ליצור" },
    {  en: "Destroy",  he: "להשמיד" },
    {  en: "Teach",  he: "ללמד" },
    {  en: "Learn",  he: "ללמוד" },
    {  en: "Study",  he: "ללמוד / ללמוד (במוסד לימודים)" },
    {  en: "Practice",  he: "לתרגל" },
    {  en: "Improve",  he: "לשפר" },
    {  en: "Help",  he: "לעזור" },
    {  en: "Ask",  he: "לשאול" },
    {  en: "Answer",  he: "לענות" },
    {  en: "Explain",  he: "להסביר" },
    {  en: "Understand",  he: "להבין" },
    {  en: "Remember",  he: "לזכור" },
    {  en: "Forget",  he: "לשכוח" },
    {  en: "Wait",  he: "לחכות" },
    {  en: "Send",  he: "לשלוח" },
    {  en: "Receive",  he: "לקבל" },
    {  en: "Call",  he: "לקרוא / להתקשר" },
    {  en: "Meet",  he: "לפגוש" },
    {  en: "Talk",  he: "לדבר" },
    {  en: "Tell",  he: "לספר" },
    {  en: "Show",  he: "להראות" },
{  en: "River",  he: "נהר" },
    {  en: "Ocean",  he: "אוקיינוס" },
    {  en: "Lake",  he: "אגם" },
    {  en: "Beach",  he: "חוף ים" },
    {  en: "Forest",  he: "יער" },
    {  en: "Desert",  he: "מדבר" },
    {  en: "Sky",  he: "שמיים" },
    {  en: "Cloud",  he: "ענן" },
    {  en: "Rain",  he: "גשם" },
    {  en: "Snow",  he: "שלג" },
    {  en: "Wind",  he: "רוח" },
    {  en: "Hot",  he: "חם" },
    {  en: "Cold",  he: "קר" },
    {  en: "Big",  he: "גדול" },
    {  en: "Small",  he: "קטן" },
    {  en: "Good",  he: "טוב" },
    {  en: "Bad",  he: "רע" },
    {  en: "Happy",  he: "שמח" },
    {  en: "Sad",  he: "עצוב" },
    {  en: "New",  he: "חדש" },
    {  en: "Old",  he: "ישן" },
    {  en: "Young",  he: "צעיר" },
    {  en: "Fast",  he: "מהיר" },
    {  en: "Slow",  he: "איטי" },
    {  en: "Clean",  he: "נקי" },
    {  en: "Dirty",  he: "מלוכלך" },
    {  en: "Easy",  he: "קל" },
    {  en: "Difficult",  he: "קשה" },
    {  en: "Right",  he: "נכון / ימין" },
    {  en: "Left",  he: "שמאל" },
    {  en: "Up",  he: "למעלה" },
    {  en: "Down",  he: "למטה" },
    {  en: "Inside",  he: "בפנים" },
    {  en: "Outside",  he: "בחוץ" },
    {  en: "Open",  he: "פתוח" },
    {  en: "Close",  he: "סגור" },
    {  en: "Walk",  he: "ללכת" },
    {  en: "Run",  he: "לרוץ" },
    {  en: "Sleep",  he: "לישון" },
    {  en: "Eat",  he: "לאכול" },
    {  en: "Drink",  he: "לשתות" },
    {  en: "Read",  he: "לקרוא" },
    {  en: "Write",  he: "לכתוב" },
    {  en: "Speak",  he: "לדבר" },
    {  en: "Listen",  he: "להקשיב" },
    {  en: "See",  he: "לראות" },
    {  en: "Hear",  he: "לשמוע" },
    {  en: "Think",  he: "לחשוב" },
    {  en: "Know",  he: "לדעת" },
    {  en: "Want",  he: "לרצות" },
{  en: "Hello",  he: "שלום" },
    {  en: "Goodbye",  he: "להתראות" },
    {  en: "Thank you",  he: "תודה" },
    {  en: "Please",  he: "בבקשה" },
    {  en: "Yes",  he: "כן" },
    {  en: "No",  he: "לא" },
    {  en: "Excuse me",  he: "סליחה" },
    {  en: "Help",  he: "הצלה" },
    {  en: "Water",  he: "מים" },
    {  en: "Food",  he: "אוכל" },
    {  en: "Friend",  he: "חבר" },
    {  en: "Love",  he: "אהבה" },
    {  en: "Family",  he: "משפחה" },
    {  en: "Home",  he: "בית" },
    {  en: "Work",  he: "עבודה" },
    {  en: "School",  he: "בית ספר" },
    {  en: "City",  he: "עיר" },
    {  en: "Country",  he: "מדינה" },
    {  en: "Book",  he: "ספר" },
    {  en: "Music",  he: "מוזיקה" },
    {  en: "Movie",  he: "סרט" },
    {  en: "Time",  he: "זמן" },
    {  en: "Day",  he: "יום" },
    {  en: "Night",  he: "לילה" },
    {  en: "Morning",  he: "בוקר" },
    {  en: "Evening",  he: "ערב" },
    {  en: "Sun",  he: "שמש" },
    {  en: "Moon",  he: "ירח" },
    {  en: "Star",  he: "כוכב" },
    {  en: "Tree",  he: "עץ" },
    {  en: "Flower",  he: "פרח" },
    {  en: "Animal",  he: "חיה" },
    {  en: "Dog",  he: "כלב" },
    {  en: "Cat",  he: "חתול" },
    {  en: "Bird",  he: "ציפור" },
    {  en: "Car",  he: "מכונית" },
    {  en: "Bus",  he: "אוטובוס" },
    {  en: "Train",  he: "רכבת" },
    {  en: "Airplane",  he: "מטוס" },
    {  en: "Money",  he: "כסף" },
    {  en: "Phone",  he: "טלפון" },
    {  en: "Computer",  he: "מחשב" },
    {  en: "Chair",  he: "כיסא" },
    {  en: "Table",  he: "שולחן" },
    {  en: "Door",  he: "דלת" },
    {  en: "Window",  he: "חלון" },
    {  en: "Street",  he: "רחוב" },
    {  en: "Road",  he: "כביש" },
    {  en: "Bridge",  he: "גשר" },
    {  en: "Mountain",  he: "הר" }]
